// flow-typed signature: a46f4bf14e5a3d4ab46562b8aa189d97
// flow-typed version: <<STUB>>/styles/buttons_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styles/buttons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styles/buttons' {
  declare module.exports: any;
}
