// flow-typed signature: 8c29cc7993247a43c1948b1bb2efaa79
// flow-typed version: <<STUB>>/styles/modals_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styles/modals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styles/modals' {
  declare module.exports: any;
}
