// flow-typed signature: f2fd0cca3a7e0a8f1ee762ceeee7de53
// flow-typed version: <<STUB>>/styles/typography_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styles/typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styles/typography' {
  declare module.exports: any;
}
