// flow-typed signature: eb5b72a9ecd7bcf4015280a2c6078f66
// flow-typed version: <<STUB>>/babel-plugin-redux-saga_v1.0.0-beta.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-redux-saga/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/declaration/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-basic/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-basic/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-basic/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-delegate/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-delegate/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-delegate/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-expression/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-expression/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-expression/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-method/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-method/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-method/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-nested/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-nested/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-nested/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-object-props/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-object-props/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/effect-object-props/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/expression/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/expression/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/expression/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/preset-env/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/preset-env/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/preset-env/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/regenerator/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/regenerator/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/regenerator/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/typescript/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/typescript/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/typescript/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/use-absolute-path/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/use-absolute-path/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/use-absolute-path/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/use-symbol/babel6-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/use-symbol/babel7-expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/fixtures/use-symbol/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-redux-saga/test/runner.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-redux-saga/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/src/index'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration-es6-modules/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration-regenerator/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/declaration/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/declaration/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-basic/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-basic/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-basic/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-basic/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-basic/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-basic/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-delegate/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-delegate/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-delegate/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-delegate/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-delegate/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-delegate/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-expression/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-expression/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-expression/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-expression/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-expression/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-expression/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-method/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-method/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-method/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-method/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-method/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-method/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-nested/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-nested/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-nested/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-nested/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-nested/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-nested/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-object-props/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-object-props/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-object-props/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-object-props/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/effect-object-props/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/effect-object-props/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/expression/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/expression/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/expression/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/expression/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/expression/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/expression/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/preset-env/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/preset-env/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/preset-env/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/preset-env/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/preset-env/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/preset-env/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/regenerator/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/regenerator/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/regenerator/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/regenerator/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/regenerator/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/regenerator/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/typescript/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/typescript/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/typescript/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/typescript/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/typescript/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/typescript/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/use-absolute-path/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/use-absolute-path/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/use-absolute-path/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/use-absolute-path/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/use-absolute-path/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/use-absolute-path/source'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/use-symbol/babel6-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/use-symbol/babel6-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/use-symbol/babel7-expected.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/use-symbol/babel7-expected'>;
}
declare module 'babel-plugin-redux-saga/test/fixtures/use-symbol/source.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/fixtures/use-symbol/source'>;
}
declare module 'babel-plugin-redux-saga/test/runner.test.js' {
  declare module.exports: $Exports<'babel-plugin-redux-saga/test/runner.test'>;
}
