// flow-typed signature: 874d3ba46b7097c36e4db137f1d258c2
// flow-typed version: <<STUB>>/calculate-size_v1.1.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'calculate-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'calculate-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'calculate-size/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'calculate-size/lib/index.js' {
  declare module.exports: $Exports<'calculate-size/lib/index'>;
}
