// flow-typed signature: 5518def106598da7337df043e0d3ee95
// flow-typed version: <<STUB>>/cz-customizable_v5.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-customizable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-customizable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cz-customizable/buildCommit' {
  declare module.exports: any;
}

declare module 'cz-customizable/cz-config-EXAMPLE' {
  declare module.exports: any;
}

declare module 'cz-customizable/questions' {
  declare module.exports: any;
}

declare module 'cz-customizable/spec/czCustomizableSpec' {
  declare module.exports: any;
}

declare module 'cz-customizable/spec/questionsSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cz-customizable/buildCommit.js' {
  declare module.exports: $Exports<'cz-customizable/buildCommit'>;
}
declare module 'cz-customizable/cz-config-EXAMPLE.js' {
  declare module.exports: $Exports<'cz-customizable/cz-config-EXAMPLE'>;
}
declare module 'cz-customizable/index' {
  declare module.exports: $Exports<'cz-customizable'>;
}
declare module 'cz-customizable/index.js' {
  declare module.exports: $Exports<'cz-customizable'>;
}
declare module 'cz-customizable/questions.js' {
  declare module.exports: $Exports<'cz-customizable/questions'>;
}
declare module 'cz-customizable/spec/czCustomizableSpec.js' {
  declare module.exports: $Exports<'cz-customizable/spec/czCustomizableSpec'>;
}
declare module 'cz-customizable/spec/questionsSpec.js' {
  declare module.exports: $Exports<'cz-customizable/spec/questionsSpec'>;
}
