// flow-typed signature: e70b5e54b52b70e0cddd335a54f145e5
// flow-typed version: <<STUB>>/electron-json-storage_v4.0.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-json-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-json-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-json-storage/lib/storage' {
  declare module.exports: any;
}

declare module 'electron-json-storage/lib/utils' {
  declare module.exports: any;
}

declare module 'electron-json-storage/tests/storage.spec' {
  declare module.exports: any;
}

declare module 'electron-json-storage/tests/utils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-json-storage/lib/storage.js' {
  declare module.exports: $Exports<'electron-json-storage/lib/storage'>;
}
declare module 'electron-json-storage/lib/utils.js' {
  declare module.exports: $Exports<'electron-json-storage/lib/utils'>;
}
declare module 'electron-json-storage/tests/storage.spec.js' {
  declare module.exports: $Exports<'electron-json-storage/tests/storage.spec'>;
}
declare module 'electron-json-storage/tests/utils.spec.js' {
  declare module.exports: $Exports<'electron-json-storage/tests/utils.spec'>;
}
