// flow-typed signature: ab7bf93151d6dc794f4bd9f9de6a9dfa
// flow-typed version: <<STUB>>/jira-connector_vgithub:web-pal/jira-connector#290772714e5ad00aa34854dcc5cd22f6a9c4ce43/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jira-connector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jira-connector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jira-connector/api/application-properties' {
  declare module.exports: any;
}

declare module 'jira-connector/api/attachment' {
  declare module.exports: any;
}

declare module 'jira-connector/api/auditing' {
  declare module.exports: any;
}

declare module 'jira-connector/api/auth' {
  declare module.exports: any;
}

declare module 'jira-connector/api/avatar' {
  declare module.exports: any;
}

declare module 'jira-connector/api/board' {
  declare module.exports: any;
}

declare module 'jira-connector/api/comment' {
  declare module.exports: any;
}

declare module 'jira-connector/api/component' {
  declare module.exports: any;
}

declare module 'jira-connector/api/customFieldOption' {
  declare module.exports: any;
}

declare module 'jira-connector/api/dashboard' {
  declare module.exports: any;
}

declare module 'jira-connector/api/field' {
  declare module.exports: any;
}

declare module 'jira-connector/api/filter' {
  declare module.exports: any;
}

declare module 'jira-connector/api/group' {
  declare module.exports: any;
}

declare module 'jira-connector/api/groups' {
  declare module.exports: any;
}

declare module 'jira-connector/api/groupUserPicker' {
  declare module.exports: any;
}

declare module 'jira-connector/api/issue' {
  declare module.exports: any;
}

declare module 'jira-connector/api/issueLink' {
  declare module.exports: any;
}

declare module 'jira-connector/api/issueLinkType' {
  declare module.exports: any;
}

declare module 'jira-connector/api/issueType' {
  declare module.exports: any;
}

declare module 'jira-connector/api/jql' {
  declare module.exports: any;
}

declare module 'jira-connector/api/licenseRole' {
  declare module.exports: any;
}

declare module 'jira-connector/api/licenseValidator' {
  declare module.exports: any;
}

declare module 'jira-connector/api/myPermissions' {
  declare module.exports: any;
}

declare module 'jira-connector/api/myPreferences' {
  declare module.exports: any;
}

declare module 'jira-connector/api/myself' {
  declare module.exports: any;
}

declare module 'jira-connector/api/password' {
  declare module.exports: any;
}

declare module 'jira-connector/api/priority' {
  declare module.exports: any;
}

declare module 'jira-connector/api/project' {
  declare module.exports: any;
}

declare module 'jira-connector/api/projectCategory' {
  declare module.exports: any;
}

declare module 'jira-connector/api/projectValidate' {
  declare module.exports: any;
}

declare module 'jira-connector/api/reindex' {
  declare module.exports: any;
}

declare module 'jira-connector/api/resolution' {
  declare module.exports: any;
}

declare module 'jira-connector/api/screens' {
  declare module.exports: any;
}

declare module 'jira-connector/api/search' {
  declare module.exports: any;
}

declare module 'jira-connector/api/securityLevel' {
  declare module.exports: any;
}

declare module 'jira-connector/api/serverInfo' {
  declare module.exports: any;
}

declare module 'jira-connector/api/settings' {
  declare module.exports: any;
}

declare module 'jira-connector/api/sprint' {
  declare module.exports: any;
}

declare module 'jira-connector/api/status' {
  declare module.exports: any;
}

declare module 'jira-connector/api/statusCategory' {
  declare module.exports: any;
}

declare module 'jira-connector/api/user' {
  declare module.exports: any;
}

declare module 'jira-connector/api/version' {
  declare module.exports: any;
}

declare module 'jira-connector/api/webhook' {
  declare module.exports: any;
}

declare module 'jira-connector/api/workflow' {
  declare module.exports: any;
}

declare module 'jira-connector/api/workflowScheme' {
  declare module.exports: any;
}

declare module 'jira-connector/api/worklog' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.10.0/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.10.0/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.10.0/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.11.0/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.11.0/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.11.0/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.0/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.0/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.0/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.1/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.1/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.1/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.2/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.2/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.4.2/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.5.0/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.5.0/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.5.0/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.6.0/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.6.0/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.6.0/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.7.0/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.7.0/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.7.0/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.8.0/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.8.0/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.8.0/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.9.0/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.9.0/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jira-connector/docs/jira-connector/1.9.0/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jira-connector/lib/error' {
  declare module.exports: any;
}

declare module 'jira-connector/lib/oauth_util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jira-connector/api/application-properties.js' {
  declare module.exports: $Exports<'jira-connector/api/application-properties'>;
}
declare module 'jira-connector/api/attachment.js' {
  declare module.exports: $Exports<'jira-connector/api/attachment'>;
}
declare module 'jira-connector/api/auditing.js' {
  declare module.exports: $Exports<'jira-connector/api/auditing'>;
}
declare module 'jira-connector/api/auth.js' {
  declare module.exports: $Exports<'jira-connector/api/auth'>;
}
declare module 'jira-connector/api/avatar.js' {
  declare module.exports: $Exports<'jira-connector/api/avatar'>;
}
declare module 'jira-connector/api/board.js' {
  declare module.exports: $Exports<'jira-connector/api/board'>;
}
declare module 'jira-connector/api/comment.js' {
  declare module.exports: $Exports<'jira-connector/api/comment'>;
}
declare module 'jira-connector/api/component.js' {
  declare module.exports: $Exports<'jira-connector/api/component'>;
}
declare module 'jira-connector/api/customFieldOption.js' {
  declare module.exports: $Exports<'jira-connector/api/customFieldOption'>;
}
declare module 'jira-connector/api/dashboard.js' {
  declare module.exports: $Exports<'jira-connector/api/dashboard'>;
}
declare module 'jira-connector/api/field.js' {
  declare module.exports: $Exports<'jira-connector/api/field'>;
}
declare module 'jira-connector/api/filter.js' {
  declare module.exports: $Exports<'jira-connector/api/filter'>;
}
declare module 'jira-connector/api/group.js' {
  declare module.exports: $Exports<'jira-connector/api/group'>;
}
declare module 'jira-connector/api/groups.js' {
  declare module.exports: $Exports<'jira-connector/api/groups'>;
}
declare module 'jira-connector/api/groupUserPicker.js' {
  declare module.exports: $Exports<'jira-connector/api/groupUserPicker'>;
}
declare module 'jira-connector/api/issue.js' {
  declare module.exports: $Exports<'jira-connector/api/issue'>;
}
declare module 'jira-connector/api/issueLink.js' {
  declare module.exports: $Exports<'jira-connector/api/issueLink'>;
}
declare module 'jira-connector/api/issueLinkType.js' {
  declare module.exports: $Exports<'jira-connector/api/issueLinkType'>;
}
declare module 'jira-connector/api/issueType.js' {
  declare module.exports: $Exports<'jira-connector/api/issueType'>;
}
declare module 'jira-connector/api/jql.js' {
  declare module.exports: $Exports<'jira-connector/api/jql'>;
}
declare module 'jira-connector/api/licenseRole.js' {
  declare module.exports: $Exports<'jira-connector/api/licenseRole'>;
}
declare module 'jira-connector/api/licenseValidator.js' {
  declare module.exports: $Exports<'jira-connector/api/licenseValidator'>;
}
declare module 'jira-connector/api/myPermissions.js' {
  declare module.exports: $Exports<'jira-connector/api/myPermissions'>;
}
declare module 'jira-connector/api/myPreferences.js' {
  declare module.exports: $Exports<'jira-connector/api/myPreferences'>;
}
declare module 'jira-connector/api/myself.js' {
  declare module.exports: $Exports<'jira-connector/api/myself'>;
}
declare module 'jira-connector/api/password.js' {
  declare module.exports: $Exports<'jira-connector/api/password'>;
}
declare module 'jira-connector/api/priority.js' {
  declare module.exports: $Exports<'jira-connector/api/priority'>;
}
declare module 'jira-connector/api/project.js' {
  declare module.exports: $Exports<'jira-connector/api/project'>;
}
declare module 'jira-connector/api/projectCategory.js' {
  declare module.exports: $Exports<'jira-connector/api/projectCategory'>;
}
declare module 'jira-connector/api/projectValidate.js' {
  declare module.exports: $Exports<'jira-connector/api/projectValidate'>;
}
declare module 'jira-connector/api/reindex.js' {
  declare module.exports: $Exports<'jira-connector/api/reindex'>;
}
declare module 'jira-connector/api/resolution.js' {
  declare module.exports: $Exports<'jira-connector/api/resolution'>;
}
declare module 'jira-connector/api/screens.js' {
  declare module.exports: $Exports<'jira-connector/api/screens'>;
}
declare module 'jira-connector/api/search.js' {
  declare module.exports: $Exports<'jira-connector/api/search'>;
}
declare module 'jira-connector/api/securityLevel.js' {
  declare module.exports: $Exports<'jira-connector/api/securityLevel'>;
}
declare module 'jira-connector/api/serverInfo.js' {
  declare module.exports: $Exports<'jira-connector/api/serverInfo'>;
}
declare module 'jira-connector/api/settings.js' {
  declare module.exports: $Exports<'jira-connector/api/settings'>;
}
declare module 'jira-connector/api/sprint.js' {
  declare module.exports: $Exports<'jira-connector/api/sprint'>;
}
declare module 'jira-connector/api/status.js' {
  declare module.exports: $Exports<'jira-connector/api/status'>;
}
declare module 'jira-connector/api/statusCategory.js' {
  declare module.exports: $Exports<'jira-connector/api/statusCategory'>;
}
declare module 'jira-connector/api/user.js' {
  declare module.exports: $Exports<'jira-connector/api/user'>;
}
declare module 'jira-connector/api/version.js' {
  declare module.exports: $Exports<'jira-connector/api/version'>;
}
declare module 'jira-connector/api/webhook.js' {
  declare module.exports: $Exports<'jira-connector/api/webhook'>;
}
declare module 'jira-connector/api/workflow.js' {
  declare module.exports: $Exports<'jira-connector/api/workflow'>;
}
declare module 'jira-connector/api/workflowScheme.js' {
  declare module.exports: $Exports<'jira-connector/api/workflowScheme'>;
}
declare module 'jira-connector/api/worklog.js' {
  declare module.exports: $Exports<'jira-connector/api/worklog'>;
}
declare module 'jira-connector/docs/jira-connector/1.10.0/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.10.0/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.10.0/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.10.0/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.10.0/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.10.0/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.11.0/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.11.0/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.11.0/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.11.0/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.11.0/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.11.0/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.0/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.0/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.0/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.0/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.0/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.0/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.1/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.1/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.1/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.1/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.1/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.1/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.2/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.2/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.2/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.2/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.4.2/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.4.2/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.5.0/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.5.0/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.5.0/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.5.0/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.5.0/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.5.0/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.6.0/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.6.0/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.6.0/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.6.0/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.6.0/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.6.0/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.7.0/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.7.0/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.7.0/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.7.0/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.7.0/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.7.0/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.8.0/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.8.0/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.8.0/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.8.0/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.8.0/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.8.0/scripts/prettify/prettify'>;
}
declare module 'jira-connector/docs/jira-connector/1.9.0/scripts/linenumber.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.9.0/scripts/linenumber'>;
}
declare module 'jira-connector/docs/jira-connector/1.9.0/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.9.0/scripts/prettify/lang-css'>;
}
declare module 'jira-connector/docs/jira-connector/1.9.0/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jira-connector/docs/jira-connector/1.9.0/scripts/prettify/prettify'>;
}
declare module 'jira-connector/index' {
  declare module.exports: $Exports<'jira-connector'>;
}
declare module 'jira-connector/index.js' {
  declare module.exports: $Exports<'jira-connector'>;
}
declare module 'jira-connector/lib/error.js' {
  declare module.exports: $Exports<'jira-connector/lib/error'>;
}
declare module 'jira-connector/lib/oauth_util.js' {
  declare module.exports: $Exports<'jira-connector/lib/oauth_util'>;
}
