// flow-typed signature: dc86f781e448da8b2a40c02f2f9b6b6a
// flow-typed version: <<STUB>>/jiraColors-util_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jiraColors-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jiraColors-util' {
  declare module.exports: any;
}
