// flow-typed signature: 21436bb8292023f7ec2b523e1d5a27f7
// flow-typed version: <<STUB>>/lodash.filter_v4.6.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.filter/index' {
  declare module.exports: $Exports<'lodash.filter'>;
}
declare module 'lodash.filter/index.js' {
  declare module.exports: $Exports<'lodash.filter'>;
}
