// flow-typed signature: 939c73daa8b7c775f41b43eaa52638a2
// flow-typed version: <<STUB>>/lodash.set_v4.3.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.set' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.set/index' {
  declare module.exports: $Exports<'lodash.set'>;
}
declare module 'lodash.set/index.js' {
  declare module.exports: $Exports<'lodash.set'>;
}
