// flow-typed signature: 8c48dab4a0fc7c521e40afc9ba72f217
// flow-typed version: <<STUB>>/merge-images_v1.0.5/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'merge-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'merge-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'merge-images/dist/index.es2015' {
  declare module.exports: any;
}

declare module 'merge-images/dist/index.umd' {
  declare module.exports: any;
}

declare module 'merge-images/rollup.config' {
  declare module.exports: any;
}

declare module 'merge-images/test/errors' {
  declare module.exports: any;
}

declare module 'merge-images/test/fixtures/index' {
  declare module.exports: any;
}

declare module 'merge-images/test/types' {
  declare module.exports: any;
}

declare module 'merge-images/test/unit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'merge-images/dist/index.es2015.js' {
  declare module.exports: $Exports<'merge-images/dist/index.es2015'>;
}
declare module 'merge-images/dist/index.umd.js' {
  declare module.exports: $Exports<'merge-images/dist/index.umd'>;
}
declare module 'merge-images/rollup.config.js' {
  declare module.exports: $Exports<'merge-images/rollup.config'>;
}
declare module 'merge-images/test/errors.js' {
  declare module.exports: $Exports<'merge-images/test/errors'>;
}
declare module 'merge-images/test/fixtures/index.js' {
  declare module.exports: $Exports<'merge-images/test/fixtures/index'>;
}
declare module 'merge-images/test/types.js' {
  declare module.exports: $Exports<'merge-images/test/types'>;
}
declare module 'merge-images/test/unit.js' {
  declare module.exports: $Exports<'merge-images/test/unit'>;
}
