// flow-typed signature: 695d4deeffc016b1211436a64ae2ba04
// flow-typed version: <<STUB>>/merge-images_v1.0.7/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'merge-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'merge-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'merge-images/dist/index.es2015' {
  declare module.exports: any;
}

declare module 'merge-images/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'merge-images/dist/index.es2015.js' {
  declare module.exports: $Exports<'merge-images/dist/index.es2015'>;
}
declare module 'merge-images/dist/index.umd.js' {
  declare module.exports: $Exports<'merge-images/dist/index.umd'>;
}
