// flow-typed signature: 8806909a80caa366a94cc390aca8ed18
// flow-typed version: <<STUB>>/mixpanel-browser_v2.13.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mixpanel-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mixpanel-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mixpanel-browser/build/mixpanel.amd' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/build/mixpanel.cjs' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/build/mixpanel.globals' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/build/mixpanel.umd' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/examples/amd-requirejs/index' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/examples/amd-requirejs/require' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/examples/commonjs-browserify/bundle' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/examples/commonjs-browserify/index' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/examples/es2015-babelify/bundle' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/examples/es2015-babelify/index' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/examples/umd-webpack/bundle' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/examples/umd-webpack/index' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/mixpanel-jslib-snippet' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/mixpanel-jslib-snippet.min' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/mixpanel-jslib-snippet.min.test' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/mixpanel.min' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/rollup.config' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/src/autotrack' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/src/config' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/src/loader-globals' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/src/loader-module' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/src/mixpanel-core' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/src/utils' {
  declare module.exports: any;
}

declare module 'mixpanel-browser/testServer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mixpanel-browser/build/mixpanel.amd.js' {
  declare module.exports: $Exports<'mixpanel-browser/build/mixpanel.amd'>;
}
declare module 'mixpanel-browser/build/mixpanel.cjs.js' {
  declare module.exports: $Exports<'mixpanel-browser/build/mixpanel.cjs'>;
}
declare module 'mixpanel-browser/build/mixpanel.globals.js' {
  declare module.exports: $Exports<'mixpanel-browser/build/mixpanel.globals'>;
}
declare module 'mixpanel-browser/build/mixpanel.umd.js' {
  declare module.exports: $Exports<'mixpanel-browser/build/mixpanel.umd'>;
}
declare module 'mixpanel-browser/examples/amd-requirejs/index.js' {
  declare module.exports: $Exports<'mixpanel-browser/examples/amd-requirejs/index'>;
}
declare module 'mixpanel-browser/examples/amd-requirejs/require.js' {
  declare module.exports: $Exports<'mixpanel-browser/examples/amd-requirejs/require'>;
}
declare module 'mixpanel-browser/examples/commonjs-browserify/bundle.js' {
  declare module.exports: $Exports<'mixpanel-browser/examples/commonjs-browserify/bundle'>;
}
declare module 'mixpanel-browser/examples/commonjs-browserify/index.js' {
  declare module.exports: $Exports<'mixpanel-browser/examples/commonjs-browserify/index'>;
}
declare module 'mixpanel-browser/examples/es2015-babelify/bundle.js' {
  declare module.exports: $Exports<'mixpanel-browser/examples/es2015-babelify/bundle'>;
}
declare module 'mixpanel-browser/examples/es2015-babelify/index.js' {
  declare module.exports: $Exports<'mixpanel-browser/examples/es2015-babelify/index'>;
}
declare module 'mixpanel-browser/examples/umd-webpack/bundle.js' {
  declare module.exports: $Exports<'mixpanel-browser/examples/umd-webpack/bundle'>;
}
declare module 'mixpanel-browser/examples/umd-webpack/index.js' {
  declare module.exports: $Exports<'mixpanel-browser/examples/umd-webpack/index'>;
}
declare module 'mixpanel-browser/mixpanel-jslib-snippet.js' {
  declare module.exports: $Exports<'mixpanel-browser/mixpanel-jslib-snippet'>;
}
declare module 'mixpanel-browser/mixpanel-jslib-snippet.min.js' {
  declare module.exports: $Exports<'mixpanel-browser/mixpanel-jslib-snippet.min'>;
}
declare module 'mixpanel-browser/mixpanel-jslib-snippet.min.test.js' {
  declare module.exports: $Exports<'mixpanel-browser/mixpanel-jslib-snippet.min.test'>;
}
declare module 'mixpanel-browser/mixpanel.min.js' {
  declare module.exports: $Exports<'mixpanel-browser/mixpanel.min'>;
}
declare module 'mixpanel-browser/rollup.config.js' {
  declare module.exports: $Exports<'mixpanel-browser/rollup.config'>;
}
declare module 'mixpanel-browser/src/autotrack.js' {
  declare module.exports: $Exports<'mixpanel-browser/src/autotrack'>;
}
declare module 'mixpanel-browser/src/config.js' {
  declare module.exports: $Exports<'mixpanel-browser/src/config'>;
}
declare module 'mixpanel-browser/src/loader-globals.js' {
  declare module.exports: $Exports<'mixpanel-browser/src/loader-globals'>;
}
declare module 'mixpanel-browser/src/loader-module.js' {
  declare module.exports: $Exports<'mixpanel-browser/src/loader-module'>;
}
declare module 'mixpanel-browser/src/mixpanel-core.js' {
  declare module.exports: $Exports<'mixpanel-browser/src/mixpanel-core'>;
}
declare module 'mixpanel-browser/src/utils.js' {
  declare module.exports: $Exports<'mixpanel-browser/src/utils'>;
}
declare module 'mixpanel-browser/testServer.js' {
  declare module.exports: $Exports<'mixpanel-browser/testServer'>;
}
