// flow-typed signature: b1ec21fc588807632da85c07eac559f3
// flow-typed version: <<STUB>>/mixpanel_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mixpanel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mixpanel' {
  declare module.exports: any;
}
