// flow-typed signature: 640b38af539634c128ad96a0ef958981
// flow-typed version: <<STUB>>/nanotimer_v0.3.15/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nanotimer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nanotimer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nanotimer/lib/nanotimer' {
  declare module.exports: any;
}

declare module 'nanotimer/test/test-nanotimer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nanotimer/lib/nanotimer.js' {
  declare module.exports: $Exports<'nanotimer/lib/nanotimer'>;
}
declare module 'nanotimer/test/test-nanotimer.js' {
  declare module.exports: $Exports<'nanotimer/test/test-nanotimer'>;
}
