// flow-typed signature: b66b98869ea6e04e713441f438003840
// flow-typed version: <<STUB>>/normalize-util_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-util' {
  declare module.exports: any;
}
