// flow-typed signature: c28d08b836348bb07cb08331b1278cc6
// flow-typed version: <<STUB>>/rc-time-picker_v2.4.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-time-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-time-picker' {
  declare module.exports: any;
}
