// flow-typed signature: 19509136bd06a2bd8ce19763b9459ec4
// flow-typed version: <<STUB>>/rc-time-picker_v3.4.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-time-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-time-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-time-picker/es/Combobox' {
  declare module.exports: any;
}

declare module 'rc-time-picker/es/Header' {
  declare module.exports: any;
}

declare module 'rc-time-picker/es/index' {
  declare module.exports: any;
}

declare module 'rc-time-picker/es/Panel' {
  declare module.exports: any;
}

declare module 'rc-time-picker/es/placements' {
  declare module.exports: any;
}

declare module 'rc-time-picker/es/Select' {
  declare module.exports: any;
}

declare module 'rc-time-picker/es/TimePicker' {
  declare module.exports: any;
}

declare module 'rc-time-picker/lib/Combobox' {
  declare module.exports: any;
}

declare module 'rc-time-picker/lib/Header' {
  declare module.exports: any;
}

declare module 'rc-time-picker/lib/index' {
  declare module.exports: any;
}

declare module 'rc-time-picker/lib/Panel' {
  declare module.exports: any;
}

declare module 'rc-time-picker/lib/placements' {
  declare module.exports: any;
}

declare module 'rc-time-picker/lib/Select' {
  declare module.exports: any;
}

declare module 'rc-time-picker/lib/TimePicker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-time-picker/es/Combobox.js' {
  declare module.exports: $Exports<'rc-time-picker/es/Combobox'>;
}
declare module 'rc-time-picker/es/Header.js' {
  declare module.exports: $Exports<'rc-time-picker/es/Header'>;
}
declare module 'rc-time-picker/es/index.js' {
  declare module.exports: $Exports<'rc-time-picker/es/index'>;
}
declare module 'rc-time-picker/es/Panel.js' {
  declare module.exports: $Exports<'rc-time-picker/es/Panel'>;
}
declare module 'rc-time-picker/es/placements.js' {
  declare module.exports: $Exports<'rc-time-picker/es/placements'>;
}
declare module 'rc-time-picker/es/Select.js' {
  declare module.exports: $Exports<'rc-time-picker/es/Select'>;
}
declare module 'rc-time-picker/es/TimePicker.js' {
  declare module.exports: $Exports<'rc-time-picker/es/TimePicker'>;
}
declare module 'rc-time-picker/lib/Combobox.js' {
  declare module.exports: $Exports<'rc-time-picker/lib/Combobox'>;
}
declare module 'rc-time-picker/lib/Header.js' {
  declare module.exports: $Exports<'rc-time-picker/lib/Header'>;
}
declare module 'rc-time-picker/lib/index.js' {
  declare module.exports: $Exports<'rc-time-picker/lib/index'>;
}
declare module 'rc-time-picker/lib/Panel.js' {
  declare module.exports: $Exports<'rc-time-picker/lib/Panel'>;
}
declare module 'rc-time-picker/lib/placements.js' {
  declare module.exports: $Exports<'rc-time-picker/lib/placements'>;
}
declare module 'rc-time-picker/lib/Select.js' {
  declare module.exports: $Exports<'rc-time-picker/lib/Select'>;
}
declare module 'rc-time-picker/lib/TimePicker.js' {
  declare module.exports: $Exports<'rc-time-picker/lib/TimePicker'>;
}
