// flow-typed signature: 1c224ead71cc1f20e55d152a4a03a91c
// flow-typed version: <<STUB>>/react-stickynode_v^1.4.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stickynode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stickynode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-stickynode/dist/Sticky' {
  declare module.exports: any;
}

declare module 'react-stickynode/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-stickynode/dist/Sticky.js' {
  declare module.exports: $Exports<'react-stickynode/dist/Sticky'>;
}
declare module 'react-stickynode/Gruntfile.js' {
  declare module.exports: $Exports<'react-stickynode/Gruntfile'>;
}
declare module 'react-stickynode/index' {
  declare module.exports: $Exports<'react-stickynode'>;
}
declare module 'react-stickynode/index.js' {
  declare module.exports: $Exports<'react-stickynode'>;
}
