// flow-typed signature: b43e05731c282e46fca2d3bf9ab3e749
// flow-typed version: <<STUB>>/react-click-outside_vgithub:tj/react-click-outside/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-click-outside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-click-outside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-click-outside/build/index' {
  declare module.exports: any;
}

declare module 'react-click-outside/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-click-outside/build/index.js' {
  declare module.exports: $Exports<'react-click-outside/build/index'>;
}
declare module 'react-click-outside/example/index.js' {
  declare module.exports: $Exports<'react-click-outside/example/index'>;
}
declare module 'react-click-outside/index' {
  declare module.exports: $Exports<'react-click-outside'>;
}
declare module 'react-click-outside/index.js' {
  declare module.exports: $Exports<'react-click-outside'>;
}
