// flow-typed signature: 114cfc5c7f3bdb3a67051247802ab064
// flow-typed version: <<STUB>>/react-click-outside_v3.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-click-outside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-click-outside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-click-outside/demo/app' {
  declare module.exports: any;
}

declare module 'react-click-outside/dist/index' {
  declare module.exports: any;
}

declare module 'react-click-outside/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-click-outside/demo/app.js' {
  declare module.exports: $Exports<'react-click-outside/demo/app'>;
}
declare module 'react-click-outside/dist/index.js' {
  declare module.exports: $Exports<'react-click-outside/dist/index'>;
}
declare module 'react-click-outside/index' {
  declare module.exports: $Exports<'react-click-outside'>;
}
declare module 'react-click-outside/index.js' {
  declare module.exports: $Exports<'react-click-outside'>;
}
declare module 'react-click-outside/test/test.js' {
  declare module.exports: $Exports<'react-click-outside/test/test'>;
}
