// flow-typed signature: 0ad1a801de40510e7406f0fad8ae20cb
// flow-typed version: <<STUB>>/redux-resource-plugins_v3.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-resource-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-resource-plugins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-resource-plugins/dist/redux-resource-plugins' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/dist/redux-resource-plugins.min' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/es/http-status-codes' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/es/included-resources' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/es/index' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/es/reset' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/es/selection' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/lib/http-status-codes' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/lib/included-resources' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/lib/index' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/lib/reset' {
  declare module.exports: any;
}

declare module 'redux-resource-plugins/lib/selection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-resource-plugins/dist/redux-resource-plugins.js' {
  declare module.exports: $Exports<'redux-resource-plugins/dist/redux-resource-plugins'>;
}
declare module 'redux-resource-plugins/dist/redux-resource-plugins.min.js' {
  declare module.exports: $Exports<'redux-resource-plugins/dist/redux-resource-plugins.min'>;
}
declare module 'redux-resource-plugins/es/http-status-codes.js' {
  declare module.exports: $Exports<'redux-resource-plugins/es/http-status-codes'>;
}
declare module 'redux-resource-plugins/es/included-resources.js' {
  declare module.exports: $Exports<'redux-resource-plugins/es/included-resources'>;
}
declare module 'redux-resource-plugins/es/index.js' {
  declare module.exports: $Exports<'redux-resource-plugins/es/index'>;
}
declare module 'redux-resource-plugins/es/reset.js' {
  declare module.exports: $Exports<'redux-resource-plugins/es/reset'>;
}
declare module 'redux-resource-plugins/es/selection.js' {
  declare module.exports: $Exports<'redux-resource-plugins/es/selection'>;
}
declare module 'redux-resource-plugins/lib/http-status-codes.js' {
  declare module.exports: $Exports<'redux-resource-plugins/lib/http-status-codes'>;
}
declare module 'redux-resource-plugins/lib/included-resources.js' {
  declare module.exports: $Exports<'redux-resource-plugins/lib/included-resources'>;
}
declare module 'redux-resource-plugins/lib/index.js' {
  declare module.exports: $Exports<'redux-resource-plugins/lib/index'>;
}
declare module 'redux-resource-plugins/lib/reset.js' {
  declare module.exports: $Exports<'redux-resource-plugins/lib/reset'>;
}
declare module 'redux-resource-plugins/lib/selection.js' {
  declare module.exports: $Exports<'redux-resource-plugins/lib/selection'>;
}
