// flow-typed signature: 12282f39721562f056a64aa03d00a250
// flow-typed version: <<STUB>>/redux-resource_v3.0.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-resource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-resource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-resource/dist/redux-resource' {
  declare module.exports: any;
}

declare module 'redux-resource/dist/redux-resource.min' {
  declare module.exports: any;
}

declare module 'redux-resource/es/action-types/action-types' {
  declare module.exports: any;
}

declare module 'redux-resource/es/action-types/deprecated' {
  declare module.exports: any;
}

declare module 'redux-resource/es/action-types/index' {
  declare module.exports: any;
}

declare module 'redux-resource/es/index' {
  declare module.exports: any;
}

declare module 'redux-resource/es/request-statuses-plugin/action-reducers-map' {
  declare module.exports: any;
}

declare module 'redux-resource/es/request-statuses-plugin/create' {
  declare module.exports: any;
}

declare module 'redux-resource/es/request-statuses-plugin/delete' {
  declare module.exports: any;
}

declare module 'redux-resource/es/request-statuses-plugin/index' {
  declare module.exports: any;
}

declare module 'redux-resource/es/request-statuses-plugin/read' {
  declare module.exports: any;
}

declare module 'redux-resource/es/request-statuses-plugin/update' {
  declare module.exports: any;
}

declare module 'redux-resource/es/resource-reducer' {
  declare module.exports: any;
}

declare module 'redux-resource/es/update-resources-plugin/index' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/compose-reducers' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/cru-reducer-helper' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/generate-default-initial-state' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/get-path-parts' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/get-resources' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/get-status' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/initial-resource-meta-state' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/reducer-generator' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/request-statuses' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/set-resource-meta' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/upsert-meta' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/upsert-resources' {
  declare module.exports: any;
}

declare module 'redux-resource/es/utils/warning' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/action-types/action-types' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/action-types/deprecated' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/action-types/index' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/index' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/request-statuses-plugin/action-reducers-map' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/request-statuses-plugin/create' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/request-statuses-plugin/delete' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/request-statuses-plugin/index' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/request-statuses-plugin/read' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/request-statuses-plugin/update' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/resource-reducer' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/update-resources-plugin/index' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/compose-reducers' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/cru-reducer-helper' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/generate-default-initial-state' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/get-path-parts' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/get-resources' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/get-status' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/initial-resource-meta-state' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/reducer-generator' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/request-statuses' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/set-resource-meta' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/upsert-meta' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/upsert-resources' {
  declare module.exports: any;
}

declare module 'redux-resource/lib/utils/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-resource/dist/redux-resource.js' {
  declare module.exports: $Exports<'redux-resource/dist/redux-resource'>;
}
declare module 'redux-resource/dist/redux-resource.min.js' {
  declare module.exports: $Exports<'redux-resource/dist/redux-resource.min'>;
}
declare module 'redux-resource/es/action-types/action-types.js' {
  declare module.exports: $Exports<'redux-resource/es/action-types/action-types'>;
}
declare module 'redux-resource/es/action-types/deprecated.js' {
  declare module.exports: $Exports<'redux-resource/es/action-types/deprecated'>;
}
declare module 'redux-resource/es/action-types/index.js' {
  declare module.exports: $Exports<'redux-resource/es/action-types/index'>;
}
declare module 'redux-resource/es/index.js' {
  declare module.exports: $Exports<'redux-resource/es/index'>;
}
declare module 'redux-resource/es/request-statuses-plugin/action-reducers-map.js' {
  declare module.exports: $Exports<'redux-resource/es/request-statuses-plugin/action-reducers-map'>;
}
declare module 'redux-resource/es/request-statuses-plugin/create.js' {
  declare module.exports: $Exports<'redux-resource/es/request-statuses-plugin/create'>;
}
declare module 'redux-resource/es/request-statuses-plugin/delete.js' {
  declare module.exports: $Exports<'redux-resource/es/request-statuses-plugin/delete'>;
}
declare module 'redux-resource/es/request-statuses-plugin/index.js' {
  declare module.exports: $Exports<'redux-resource/es/request-statuses-plugin/index'>;
}
declare module 'redux-resource/es/request-statuses-plugin/read.js' {
  declare module.exports: $Exports<'redux-resource/es/request-statuses-plugin/read'>;
}
declare module 'redux-resource/es/request-statuses-plugin/update.js' {
  declare module.exports: $Exports<'redux-resource/es/request-statuses-plugin/update'>;
}
declare module 'redux-resource/es/resource-reducer.js' {
  declare module.exports: $Exports<'redux-resource/es/resource-reducer'>;
}
declare module 'redux-resource/es/update-resources-plugin/index.js' {
  declare module.exports: $Exports<'redux-resource/es/update-resources-plugin/index'>;
}
declare module 'redux-resource/es/utils/compose-reducers.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/compose-reducers'>;
}
declare module 'redux-resource/es/utils/cru-reducer-helper.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/cru-reducer-helper'>;
}
declare module 'redux-resource/es/utils/generate-default-initial-state.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/generate-default-initial-state'>;
}
declare module 'redux-resource/es/utils/get-path-parts.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/get-path-parts'>;
}
declare module 'redux-resource/es/utils/get-resources.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/get-resources'>;
}
declare module 'redux-resource/es/utils/get-status.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/get-status'>;
}
declare module 'redux-resource/es/utils/initial-resource-meta-state.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/initial-resource-meta-state'>;
}
declare module 'redux-resource/es/utils/reducer-generator.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/reducer-generator'>;
}
declare module 'redux-resource/es/utils/request-statuses.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/request-statuses'>;
}
declare module 'redux-resource/es/utils/set-resource-meta.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/set-resource-meta'>;
}
declare module 'redux-resource/es/utils/upsert-meta.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/upsert-meta'>;
}
declare module 'redux-resource/es/utils/upsert-resources.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/upsert-resources'>;
}
declare module 'redux-resource/es/utils/warning.js' {
  declare module.exports: $Exports<'redux-resource/es/utils/warning'>;
}
declare module 'redux-resource/lib/action-types/action-types.js' {
  declare module.exports: $Exports<'redux-resource/lib/action-types/action-types'>;
}
declare module 'redux-resource/lib/action-types/deprecated.js' {
  declare module.exports: $Exports<'redux-resource/lib/action-types/deprecated'>;
}
declare module 'redux-resource/lib/action-types/index.js' {
  declare module.exports: $Exports<'redux-resource/lib/action-types/index'>;
}
declare module 'redux-resource/lib/index.js' {
  declare module.exports: $Exports<'redux-resource/lib/index'>;
}
declare module 'redux-resource/lib/request-statuses-plugin/action-reducers-map.js' {
  declare module.exports: $Exports<'redux-resource/lib/request-statuses-plugin/action-reducers-map'>;
}
declare module 'redux-resource/lib/request-statuses-plugin/create.js' {
  declare module.exports: $Exports<'redux-resource/lib/request-statuses-plugin/create'>;
}
declare module 'redux-resource/lib/request-statuses-plugin/delete.js' {
  declare module.exports: $Exports<'redux-resource/lib/request-statuses-plugin/delete'>;
}
declare module 'redux-resource/lib/request-statuses-plugin/index.js' {
  declare module.exports: $Exports<'redux-resource/lib/request-statuses-plugin/index'>;
}
declare module 'redux-resource/lib/request-statuses-plugin/read.js' {
  declare module.exports: $Exports<'redux-resource/lib/request-statuses-plugin/read'>;
}
declare module 'redux-resource/lib/request-statuses-plugin/update.js' {
  declare module.exports: $Exports<'redux-resource/lib/request-statuses-plugin/update'>;
}
declare module 'redux-resource/lib/resource-reducer.js' {
  declare module.exports: $Exports<'redux-resource/lib/resource-reducer'>;
}
declare module 'redux-resource/lib/update-resources-plugin/index.js' {
  declare module.exports: $Exports<'redux-resource/lib/update-resources-plugin/index'>;
}
declare module 'redux-resource/lib/utils/compose-reducers.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/compose-reducers'>;
}
declare module 'redux-resource/lib/utils/cru-reducer-helper.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/cru-reducer-helper'>;
}
declare module 'redux-resource/lib/utils/generate-default-initial-state.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/generate-default-initial-state'>;
}
declare module 'redux-resource/lib/utils/get-path-parts.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/get-path-parts'>;
}
declare module 'redux-resource/lib/utils/get-resources.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/get-resources'>;
}
declare module 'redux-resource/lib/utils/get-status.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/get-status'>;
}
declare module 'redux-resource/lib/utils/initial-resource-meta-state.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/initial-resource-meta-state'>;
}
declare module 'redux-resource/lib/utils/reducer-generator.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/reducer-generator'>;
}
declare module 'redux-resource/lib/utils/request-statuses.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/request-statuses'>;
}
declare module 'redux-resource/lib/utils/set-resource-meta.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/set-resource-meta'>;
}
declare module 'redux-resource/lib/utils/upsert-meta.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/upsert-meta'>;
}
declare module 'redux-resource/lib/utils/upsert-resources.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/upsert-resources'>;
}
declare module 'redux-resource/lib/utils/warning.js' {
  declare module.exports: $Exports<'redux-resource/lib/utils/warning'>;
}
