// flow-typed signature: f66e33712657ec60a9dd6b4c49046719
// flow-typed version: <<STUB>>/redux-resource-action-creators_v1.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-resource-action-creators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-resource-action-creators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-resource-action-creators/dist/redux-resource-prop-types' {
  declare module.exports: any;
}

declare module 'redux-resource-action-creators/dist/redux-resource-prop-types.min' {
  declare module.exports: any;
}

declare module 'redux-resource-action-creators/es/index' {
  declare module.exports: any;
}

declare module 'redux-resource-action-creators/es/utils/warning' {
  declare module.exports: any;
}

declare module 'redux-resource-action-creators/lib/index' {
  declare module.exports: any;
}

declare module 'redux-resource-action-creators/lib/utils/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-resource-action-creators/dist/redux-resource-prop-types.js' {
  declare module.exports: $Exports<'redux-resource-action-creators/dist/redux-resource-prop-types'>;
}
declare module 'redux-resource-action-creators/dist/redux-resource-prop-types.min.js' {
  declare module.exports: $Exports<'redux-resource-action-creators/dist/redux-resource-prop-types.min'>;
}
declare module 'redux-resource-action-creators/es/index.js' {
  declare module.exports: $Exports<'redux-resource-action-creators/es/index'>;
}
declare module 'redux-resource-action-creators/es/utils/warning.js' {
  declare module.exports: $Exports<'redux-resource-action-creators/es/utils/warning'>;
}
declare module 'redux-resource-action-creators/lib/index.js' {
  declare module.exports: $Exports<'redux-resource-action-creators/lib/index'>;
}
declare module 'redux-resource-action-creators/lib/utils/warning.js' {
  declare module.exports: $Exports<'redux-resource-action-creators/lib/utils/warning'>;
}
