// flow-typed signature: 9d1da9efd13318e557d2b6c7a6a594eb
// flow-typed version: <<STUB>>/styles_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styles' {
  declare module.exports: any;
}
