// flow-typed signature: a360d2b90239e56b3b6b4b2d805b62e3
// flow-typed version: <<STUB>>/svg-inline-loader_v0.8.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-inline-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-inline-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-inline-loader/config' {
  declare module.exports: any;
}

declare module 'svg-inline-loader/lib/component' {
  declare module.exports: any;
}

declare module 'svg-inline-loader/lib/conditions' {
  declare module.exports: any;
}

declare module 'svg-inline-loader/lib/transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-inline-loader/config.js' {
  declare module.exports: $Exports<'svg-inline-loader/config'>;
}
declare module 'svg-inline-loader/index' {
  declare module.exports: $Exports<'svg-inline-loader'>;
}
declare module 'svg-inline-loader/index.js' {
  declare module.exports: $Exports<'svg-inline-loader'>;
}
declare module 'svg-inline-loader/lib/component.jsx' {
  declare module.exports: $Exports<'svg-inline-loader/lib/component'>;
}
declare module 'svg-inline-loader/lib/conditions.js' {
  declare module.exports: $Exports<'svg-inline-loader/lib/conditions'>;
}
declare module 'svg-inline-loader/lib/transformer.js' {
  declare module.exports: $Exports<'svg-inline-loader/lib/transformer'>;
}
