// flow-typed signature: 2debf079231b5db8bdb101ec206c37e1
// flow-typed version: <<STUB>>/timer-helper_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timer-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timer-helper' {
  declare module.exports: any;
}
