// flow-typed signature: e02c587c23c998434b1a7f033dfca450
// flow-typed version: <<STUB>>/time-util_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'time-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'time-util' {
  declare module.exports: any;
}
