// flow-typed signature: d7fdf14403922d5104cb29713121cc63
// flow-typed version: <<STUB>>/tough-cookie_v^2.4.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tough-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tough-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tough-cookie/lib/cookie' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/memstore' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/pathMatch' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/permuteDomain' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/pubsuffix-psl' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tough-cookie/lib/cookie.js' {
  declare module.exports: $Exports<'tough-cookie/lib/cookie'>;
}
declare module 'tough-cookie/lib/memstore.js' {
  declare module.exports: $Exports<'tough-cookie/lib/memstore'>;
}
declare module 'tough-cookie/lib/pathMatch.js' {
  declare module.exports: $Exports<'tough-cookie/lib/pathMatch'>;
}
declare module 'tough-cookie/lib/permuteDomain.js' {
  declare module.exports: $Exports<'tough-cookie/lib/permuteDomain'>;
}
declare module 'tough-cookie/lib/pubsuffix-psl.js' {
  declare module.exports: $Exports<'tough-cookie/lib/pubsuffix-psl'>;
}
declare module 'tough-cookie/lib/store.js' {
  declare module.exports: $Exports<'tough-cookie/lib/store'>;
}
