// flow-typed signature: eb2528b3fd0ae12f27e74a702c24110a
// flow-typed version: <<STUB>>/webpack-sentry-plugin_v1.16.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-sentry-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-sentry-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-sentry-plugin/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-sentry-plugin/dist/index.js' {
  declare module.exports: $Exports<'webpack-sentry-plugin/dist/index'>;
}
