// flow-typed signature: 3a20b0b3068da5662ce542c4b84b908d
// flow-typed version: <<STUB>>/write-file-webpack-plugin_v^4.4.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'write-file-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'write-file-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'write-file-webpack-plugin/dist/WriteFileWebpackPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'write-file-webpack-plugin/dist/WriteFileWebpackPlugin.js' {
  declare module.exports: $Exports<'write-file-webpack-plugin/dist/WriteFileWebpackPlugin'>;
}
