// flow-typed signature: 55f356ce4cbecd35615f18fd2e06f092
// flow-typed version: <<STUB>>/@atlaskit/button_v6.3.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/button/dist/cjs/components/Button' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/components/ButtonGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/components/CustomComponentProxy' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/components/getButtonProps' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/components/withDeprecationWarnings' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/styled/ButtonContent' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/styled/ButtonGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/styled/ButtonWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/styled/getButtonStyles' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/styled/IconWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/styled/themeDefinitions' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/theme' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/components/Button' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/components/ButtonGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/components/CustomComponentProxy' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/components/getButtonProps' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/components/withDeprecationWarnings' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/styled/ButtonContent' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/styled/ButtonGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/styled/ButtonWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/styled/getButtonStyles' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/styled/IconWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/styled/themeDefinitions' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/theme' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/button/dist/cjs/components/Button.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/components/Button'>;
}
declare module '@atlaskit/button/dist/cjs/components/ButtonGroup.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/components/ButtonGroup'>;
}
declare module '@atlaskit/button/dist/cjs/components/CustomComponentProxy.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/components/CustomComponentProxy'>;
}
declare module '@atlaskit/button/dist/cjs/components/getButtonProps.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/components/getButtonProps'>;
}
declare module '@atlaskit/button/dist/cjs/components/withDeprecationWarnings.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/components/withDeprecationWarnings'>;
}
declare module '@atlaskit/button/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/index'>;
}
declare module '@atlaskit/button/dist/cjs/styled/ButtonContent.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/styled/ButtonContent'>;
}
declare module '@atlaskit/button/dist/cjs/styled/ButtonGroup.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/styled/ButtonGroup'>;
}
declare module '@atlaskit/button/dist/cjs/styled/ButtonWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/styled/ButtonWrapper'>;
}
declare module '@atlaskit/button/dist/cjs/styled/getButtonStyles.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/styled/getButtonStyles'>;
}
declare module '@atlaskit/button/dist/cjs/styled/IconWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/styled/IconWrapper'>;
}
declare module '@atlaskit/button/dist/cjs/styled/themeDefinitions.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/styled/themeDefinitions'>;
}
declare module '@atlaskit/button/dist/cjs/theme.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/theme'>;
}
declare module '@atlaskit/button/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/cjs/types'>;
}
declare module '@atlaskit/button/dist/esm/components/Button.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/components/Button'>;
}
declare module '@atlaskit/button/dist/esm/components/ButtonGroup.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/components/ButtonGroup'>;
}
declare module '@atlaskit/button/dist/esm/components/CustomComponentProxy.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/components/CustomComponentProxy'>;
}
declare module '@atlaskit/button/dist/esm/components/getButtonProps.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/components/getButtonProps'>;
}
declare module '@atlaskit/button/dist/esm/components/withDeprecationWarnings.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/components/withDeprecationWarnings'>;
}
declare module '@atlaskit/button/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/index'>;
}
declare module '@atlaskit/button/dist/esm/styled/ButtonContent.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/styled/ButtonContent'>;
}
declare module '@atlaskit/button/dist/esm/styled/ButtonGroup.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/styled/ButtonGroup'>;
}
declare module '@atlaskit/button/dist/esm/styled/ButtonWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/styled/ButtonWrapper'>;
}
declare module '@atlaskit/button/dist/esm/styled/getButtonStyles.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/styled/getButtonStyles'>;
}
declare module '@atlaskit/button/dist/esm/styled/IconWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/styled/IconWrapper'>;
}
declare module '@atlaskit/button/dist/esm/styled/themeDefinitions.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/styled/themeDefinitions'>;
}
declare module '@atlaskit/button/dist/esm/theme.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/theme'>;
}
declare module '@atlaskit/button/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/esm/types'>;
}
