// flow-typed signature: 3e7c54d072fb610f389e2fcc792b6a30
// flow-typed version: <<STUB>>/@atlaskit/button_v5.4.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/button/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/components/Button' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/components/ButtonGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/components/CustomComponentProxy' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/components/getButtonProps' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/styled/ButtonContent' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/styled/ButtonGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/styled/ButtonWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/styled/getButtonStyles' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/styled/IconWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/button/dist/es/styled/themeDefinitions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/button/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/bundle-cjs'>;
}
declare module '@atlaskit/button/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/button/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/bundle'>;
}
declare module '@atlaskit/button/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/bundle.min'>;
}
declare module '@atlaskit/button/dist/es/components/Button.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/components/Button'>;
}
declare module '@atlaskit/button/dist/es/components/ButtonGroup.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/components/ButtonGroup'>;
}
declare module '@atlaskit/button/dist/es/components/CustomComponentProxy.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/components/CustomComponentProxy'>;
}
declare module '@atlaskit/button/dist/es/components/getButtonProps.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/components/getButtonProps'>;
}
declare module '@atlaskit/button/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/index'>;
}
declare module '@atlaskit/button/dist/es/styled/ButtonContent.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/styled/ButtonContent'>;
}
declare module '@atlaskit/button/dist/es/styled/ButtonGroup.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/styled/ButtonGroup'>;
}
declare module '@atlaskit/button/dist/es/styled/ButtonWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/styled/ButtonWrapper'>;
}
declare module '@atlaskit/button/dist/es/styled/getButtonStyles.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/styled/getButtonStyles'>;
}
declare module '@atlaskit/button/dist/es/styled/IconWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/styled/IconWrapper'>;
}
declare module '@atlaskit/button/dist/es/styled/themeDefinitions.js' {
  declare module.exports: $Exports<'@atlaskit/button/dist/es/styled/themeDefinitions'>;
}
