// flow-typed signature: c8bba7471fba535738bd7c9e12bbe807
// flow-typed version: <<STUB>>/@atlaskit/button-group_v1.5.3/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/button-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/button-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/button-group/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/button-group/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/button-group/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/button-group/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/button-group/dist/es/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/button-group/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/button-group/dist/bundle-cjs'>;
}
declare module '@atlaskit/button-group/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/button-group/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/button-group/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/button-group/dist/bundle'>;
}
declare module '@atlaskit/button-group/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/button-group/dist/bundle.min'>;
}
declare module '@atlaskit/button-group/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/button-group/dist/es/index'>;
}
