// flow-typed signature: 688c94cf1b963f811ef61ad69713fa1f
// flow-typed version: <<STUB>>/@atlaskit/calendar_v3.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/calendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/calendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/calendar/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/components/Btn' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/components/Calendar' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/components/CalendarStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/components/Date' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/components/Heading' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/styled/Calendar' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/styled/Date' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/styled/Heading' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/es/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/calendar/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/bundle-cjs'>;
}
declare module '@atlaskit/calendar/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/calendar/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/bundle'>;
}
declare module '@atlaskit/calendar/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/bundle.min'>;
}
declare module '@atlaskit/calendar/dist/es/components/Btn.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/components/Btn'>;
}
declare module '@atlaskit/calendar/dist/es/components/Calendar.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/components/Calendar'>;
}
declare module '@atlaskit/calendar/dist/es/components/CalendarStateless.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/components/CalendarStateless'>;
}
declare module '@atlaskit/calendar/dist/es/components/Date.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/components/Date'>;
}
declare module '@atlaskit/calendar/dist/es/components/Heading.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/components/Heading'>;
}
declare module '@atlaskit/calendar/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/index'>;
}
declare module '@atlaskit/calendar/dist/es/styled/Calendar.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/styled/Calendar'>;
}
declare module '@atlaskit/calendar/dist/es/styled/Date.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/styled/Date'>;
}
declare module '@atlaskit/calendar/dist/es/styled/Heading.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/styled/Heading'>;
}
declare module '@atlaskit/calendar/dist/es/util.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/es/util'>;
}
