// flow-typed signature: 015201bda5b57ca6c2d4b4cf5c3c2f7a
// flow-typed version: <<STUB>>/@atlaskit/calendar_v3.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/calendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/calendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/calendar/dist/cjs/components/Btn' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/components/Calendar' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/components/CalendarStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/components/Date' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/components/Heading' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/styled/Calendar' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/styled/Date' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/styled/Heading' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/cjs/util/index' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/components/Btn' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/components/Calendar' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/components/CalendarStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/components/Date' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/components/Heading' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/styled/Calendar' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/styled/Date' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/styled/Heading' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/types' {
  declare module.exports: any;
}

declare module '@atlaskit/calendar/dist/esm/util/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/calendar/dist/cjs/components/Btn.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/components/Btn'>;
}
declare module '@atlaskit/calendar/dist/cjs/components/Calendar.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/components/Calendar'>;
}
declare module '@atlaskit/calendar/dist/cjs/components/CalendarStateless.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/components/CalendarStateless'>;
}
declare module '@atlaskit/calendar/dist/cjs/components/Date.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/components/Date'>;
}
declare module '@atlaskit/calendar/dist/cjs/components/Heading.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/components/Heading'>;
}
declare module '@atlaskit/calendar/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/index'>;
}
declare module '@atlaskit/calendar/dist/cjs/styled/Calendar.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/styled/Calendar'>;
}
declare module '@atlaskit/calendar/dist/cjs/styled/Date.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/styled/Date'>;
}
declare module '@atlaskit/calendar/dist/cjs/styled/Heading.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/styled/Heading'>;
}
declare module '@atlaskit/calendar/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/types'>;
}
declare module '@atlaskit/calendar/dist/cjs/util/index.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/cjs/util/index'>;
}
declare module '@atlaskit/calendar/dist/esm/components/Btn.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/components/Btn'>;
}
declare module '@atlaskit/calendar/dist/esm/components/Calendar.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/components/Calendar'>;
}
declare module '@atlaskit/calendar/dist/esm/components/CalendarStateless.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/components/CalendarStateless'>;
}
declare module '@atlaskit/calendar/dist/esm/components/Date.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/components/Date'>;
}
declare module '@atlaskit/calendar/dist/esm/components/Heading.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/components/Heading'>;
}
declare module '@atlaskit/calendar/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/index'>;
}
declare module '@atlaskit/calendar/dist/esm/styled/Calendar.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/styled/Calendar'>;
}
declare module '@atlaskit/calendar/dist/esm/styled/Date.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/styled/Date'>;
}
declare module '@atlaskit/calendar/dist/esm/styled/Heading.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/styled/Heading'>;
}
declare module '@atlaskit/calendar/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/types'>;
}
declare module '@atlaskit/calendar/dist/esm/util/index.js' {
  declare module.exports: $Exports<'@atlaskit/calendar/dist/esm/util/index'>;
}
