// flow-typed signature: f06f3d5e4f6f96e80f1a3f348b100946
// flow-typed version: <<STUB>>/@atlaskit/checkbox_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/checkbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/checkbox/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/es/Checkbox' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/es/CheckboxGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/es/CheckboxStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/es/styled/Checkbox' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/es/styled/CheckboxGroup' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/checkbox/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/bundle-cjs'>;
}
declare module '@atlaskit/checkbox/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/checkbox/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/bundle'>;
}
declare module '@atlaskit/checkbox/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/bundle.min'>;
}
declare module '@atlaskit/checkbox/dist/es/Checkbox.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/es/Checkbox'>;
}
declare module '@atlaskit/checkbox/dist/es/CheckboxGroup.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/es/CheckboxGroup'>;
}
declare module '@atlaskit/checkbox/dist/es/CheckboxStateless.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/es/CheckboxStateless'>;
}
declare module '@atlaskit/checkbox/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/es/index'>;
}
declare module '@atlaskit/checkbox/dist/es/styled/Checkbox.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/es/styled/Checkbox'>;
}
declare module '@atlaskit/checkbox/dist/es/styled/CheckboxGroup.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/es/styled/CheckboxGroup'>;
}
