// flow-typed signature: c48d0d05f76c7b354c25cf3b70e9dfb9
// flow-typed version: <<STUB>>/@atlaskit/checkbox_v1.2.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/checkbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/checkbox/dist/cjs/Checkbox' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/cjs/CheckboxGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/cjs/CheckboxStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/cjs/styled/Checkbox' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/cjs/styled/CheckboxGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/esm/Checkbox' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/esm/CheckboxGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/esm/CheckboxStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/esm/styled/Checkbox' {
  declare module.exports: any;
}

declare module '@atlaskit/checkbox/dist/esm/styled/CheckboxGroup' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/checkbox/dist/cjs/Checkbox.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/cjs/Checkbox'>;
}
declare module '@atlaskit/checkbox/dist/cjs/CheckboxGroup.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/cjs/CheckboxGroup'>;
}
declare module '@atlaskit/checkbox/dist/cjs/CheckboxStateless.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/cjs/CheckboxStateless'>;
}
declare module '@atlaskit/checkbox/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/cjs/index'>;
}
declare module '@atlaskit/checkbox/dist/cjs/styled/Checkbox.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/cjs/styled/Checkbox'>;
}
declare module '@atlaskit/checkbox/dist/cjs/styled/CheckboxGroup.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/cjs/styled/CheckboxGroup'>;
}
declare module '@atlaskit/checkbox/dist/esm/Checkbox.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/esm/Checkbox'>;
}
declare module '@atlaskit/checkbox/dist/esm/CheckboxGroup.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/esm/CheckboxGroup'>;
}
declare module '@atlaskit/checkbox/dist/esm/CheckboxStateless.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/esm/CheckboxStateless'>;
}
declare module '@atlaskit/checkbox/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/esm/index'>;
}
declare module '@atlaskit/checkbox/dist/esm/styled/Checkbox.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/esm/styled/Checkbox'>;
}
declare module '@atlaskit/checkbox/dist/esm/styled/CheckboxGroup.js' {
  declare module.exports: $Exports<'@atlaskit/checkbox/dist/esm/styled/CheckboxGroup'>;
}
