// flow-typed signature: 108d0b0a0068442f560579b18cf49278
// flow-typed version: <<STUB>>/@atlaskit/dropdown-menu_v3.11.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/dropdown-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/dropdown-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemClickManager' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemFocusManager' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemSelectionCache' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemSelectionManager' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/DropdownMenu' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/DropdownMenuStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroupCheckbox' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroupRadio' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/hoc/withItemSelectionManager' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/hoc/withToggleInteraction' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItem' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItemCheckbox' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItemRadio' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/styled/WidthConstrainer' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/util/contextNamespace' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/util/getDisplayName' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/util/keys' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/util/safeContextCall' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/cjs/util/supportsVoiceover' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemClickManager' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemFocusManager' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemSelectionCache' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemSelectionManager' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/DropdownMenu' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/DropdownMenuStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroupCheckbox' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroupRadio' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/hoc/withItemSelectionManager' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/hoc/withToggleInteraction' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItem' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItemCheckbox' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItemRadio' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/styled/WidthConstrainer' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/types' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/util/contextNamespace' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/util/getDisplayName' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/util/keys' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/util/safeContextCall' {
  declare module.exports: any;
}

declare module '@atlaskit/dropdown-menu/dist/esm/util/supportsVoiceover' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemClickManager.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemClickManager'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemFocusManager.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemFocusManager'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemSelectionCache.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemSelectionCache'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemSelectionManager.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/context/DropdownItemSelectionManager'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/DropdownMenu.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/DropdownMenu'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/DropdownMenuStateless.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/DropdownMenuStateless'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroup.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroup'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroupCheckbox.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroupCheckbox'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroupRadio.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/group/DropdownItemGroupRadio'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/hoc/withItemSelectionManager.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/hoc/withItemSelectionManager'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/hoc/withToggleInteraction.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/hoc/withToggleInteraction'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItem.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItem'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItemCheckbox.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItemCheckbox'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItemRadio.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/components/item/DropdownItemRadio'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/index'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/styled/WidthConstrainer.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/styled/WidthConstrainer'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/types'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/util/contextNamespace.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/util/contextNamespace'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/util/getDisplayName.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/util/getDisplayName'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/util/keys.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/util/keys'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/util/safeContextCall.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/util/safeContextCall'>;
}
declare module '@atlaskit/dropdown-menu/dist/cjs/util/supportsVoiceover.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/cjs/util/supportsVoiceover'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemClickManager.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemClickManager'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemFocusManager.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemFocusManager'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemSelectionCache.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemSelectionCache'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemSelectionManager.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/context/DropdownItemSelectionManager'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/DropdownMenu.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/DropdownMenu'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/DropdownMenuStateless.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/DropdownMenuStateless'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroup.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroup'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroupCheckbox.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroupCheckbox'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroupRadio.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/group/DropdownItemGroupRadio'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/hoc/withItemSelectionManager.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/hoc/withItemSelectionManager'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/hoc/withToggleInteraction.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/hoc/withToggleInteraction'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItem.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItem'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItemCheckbox.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItemCheckbox'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItemRadio.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/components/item/DropdownItemRadio'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/index'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/styled/WidthConstrainer.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/styled/WidthConstrainer'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/types'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/util/contextNamespace.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/util/contextNamespace'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/util/getDisplayName.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/util/getDisplayName'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/util/keys.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/util/keys'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/util/safeContextCall.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/util/safeContextCall'>;
}
declare module '@atlaskit/dropdown-menu/dist/esm/util/supportsVoiceover.js' {
  declare module.exports: $Exports<'@atlaskit/dropdown-menu/dist/esm/util/supportsVoiceover'>;
}
