// flow-typed signature: dedd798a75de4706d85e7a4bcf9b9e32
// flow-typed version: <<STUB>>/@atlaskit/field-radio-group_v1.6.4/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/field-radio-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/field-radio-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/field-radio-group/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/components/constants' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/components/Radio' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/components/RadioGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/components/RadioGroupStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/styled/constants' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/styled/Radio' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/styled/RadioIcon' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/styled/RadioIconCheckedIndicator' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/es/styled/theme' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/field-radio-group/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/bundle-cjs'>;
}
declare module '@atlaskit/field-radio-group/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/field-radio-group/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/bundle'>;
}
declare module '@atlaskit/field-radio-group/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/bundle.min'>;
}
declare module '@atlaskit/field-radio-group/dist/es/components/constants.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/components/constants'>;
}
declare module '@atlaskit/field-radio-group/dist/es/components/Radio.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/components/Radio'>;
}
declare module '@atlaskit/field-radio-group/dist/es/components/RadioGroup.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/components/RadioGroup'>;
}
declare module '@atlaskit/field-radio-group/dist/es/components/RadioGroupStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/components/RadioGroupStateless'>;
}
declare module '@atlaskit/field-radio-group/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/index'>;
}
declare module '@atlaskit/field-radio-group/dist/es/styled/constants.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/styled/constants'>;
}
declare module '@atlaskit/field-radio-group/dist/es/styled/Radio.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/styled/Radio'>;
}
declare module '@atlaskit/field-radio-group/dist/es/styled/RadioIcon.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/styled/RadioIcon'>;
}
declare module '@atlaskit/field-radio-group/dist/es/styled/RadioIconCheckedIndicator.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/styled/RadioIconCheckedIndicator'>;
}
declare module '@atlaskit/field-radio-group/dist/es/styled/theme.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/es/styled/theme'>;
}
