// flow-typed signature: 47ef6414a9fd1985a8f2d77fa142d62e
// flow-typed version: <<STUB>>/@atlaskit/field-radio-group_v1.8.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/field-radio-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/field-radio-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/field-radio-group/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/cjs/Radio' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/cjs/RadioBase' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/cjs/RadioGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/cjs/RadioGroupStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/cjs/styled/constants' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/cjs/styled/Radio' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/esm/Radio' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/esm/RadioBase' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/esm/RadioGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/esm/RadioGroupStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/esm/styled/constants' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/esm/styled/Radio' {
  declare module.exports: any;
}

declare module '@atlaskit/field-radio-group/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/field-radio-group/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/cjs/index'>;
}
declare module '@atlaskit/field-radio-group/dist/cjs/Radio.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/cjs/Radio'>;
}
declare module '@atlaskit/field-radio-group/dist/cjs/RadioBase.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/cjs/RadioBase'>;
}
declare module '@atlaskit/field-radio-group/dist/cjs/RadioGroup.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/cjs/RadioGroup'>;
}
declare module '@atlaskit/field-radio-group/dist/cjs/RadioGroupStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/cjs/RadioGroupStateless'>;
}
declare module '@atlaskit/field-radio-group/dist/cjs/styled/constants.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/cjs/styled/constants'>;
}
declare module '@atlaskit/field-radio-group/dist/cjs/styled/Radio.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/cjs/styled/Radio'>;
}
declare module '@atlaskit/field-radio-group/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/cjs/types'>;
}
declare module '@atlaskit/field-radio-group/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/esm/index'>;
}
declare module '@atlaskit/field-radio-group/dist/esm/Radio.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/esm/Radio'>;
}
declare module '@atlaskit/field-radio-group/dist/esm/RadioBase.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/esm/RadioBase'>;
}
declare module '@atlaskit/field-radio-group/dist/esm/RadioGroup.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/esm/RadioGroup'>;
}
declare module '@atlaskit/field-radio-group/dist/esm/RadioGroupStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/esm/RadioGroupStateless'>;
}
declare module '@atlaskit/field-radio-group/dist/esm/styled/constants.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/esm/styled/constants'>;
}
declare module '@atlaskit/field-radio-group/dist/esm/styled/Radio.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/esm/styled/Radio'>;
}
declare module '@atlaskit/field-radio-group/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/field-radio-group/dist/esm/types'>;
}
