// flow-typed signature: ec62a0c0beab64719cefe0c480566adb
// flow-typed version: <<STUB>>/@atlaskit/field-base_v8.1.9/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/field-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/field-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/field-base/dist/cjs/components/FieldBase' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/cjs/components/FieldBaseStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/cjs/components/Label' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/cjs/components/ValidationElement' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/cjs/styled/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/cjs/styled/Label' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/cjs/styled/theme' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/components/FieldBase' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/components/FieldBaseStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/components/Label' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/components/ValidationElement' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/styled/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/styled/Label' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/styled/theme' {
  declare module.exports: any;
}

declare module '@atlaskit/field-base/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/field-base/dist/cjs/components/FieldBase.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/components/FieldBase'>;
}
declare module '@atlaskit/field-base/dist/cjs/components/FieldBaseStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/components/FieldBaseStateless'>;
}
declare module '@atlaskit/field-base/dist/cjs/components/Label.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/components/Label'>;
}
declare module '@atlaskit/field-base/dist/cjs/components/ValidationElement.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/components/ValidationElement'>;
}
declare module '@atlaskit/field-base/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/index'>;
}
declare module '@atlaskit/field-base/dist/cjs/styled/Content.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/styled/Content'>;
}
declare module '@atlaskit/field-base/dist/cjs/styled/Label.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/styled/Label'>;
}
declare module '@atlaskit/field-base/dist/cjs/styled/theme.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/styled/theme'>;
}
declare module '@atlaskit/field-base/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/cjs/types'>;
}
declare module '@atlaskit/field-base/dist/esm/components/FieldBase.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/components/FieldBase'>;
}
declare module '@atlaskit/field-base/dist/esm/components/FieldBaseStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/components/FieldBaseStateless'>;
}
declare module '@atlaskit/field-base/dist/esm/components/Label.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/components/Label'>;
}
declare module '@atlaskit/field-base/dist/esm/components/ValidationElement.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/components/ValidationElement'>;
}
declare module '@atlaskit/field-base/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/index'>;
}
declare module '@atlaskit/field-base/dist/esm/styled/Content.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/styled/Content'>;
}
declare module '@atlaskit/field-base/dist/esm/styled/Label.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/styled/Label'>;
}
declare module '@atlaskit/field-base/dist/esm/styled/theme.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/styled/theme'>;
}
declare module '@atlaskit/field-base/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/field-base/dist/esm/types'>;
}
