// flow-typed signature: 81ef7aba2699d8fa549f41e72c5d302b
// flow-typed version: <<STUB>>/@atlaskit/field-text-area_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/field-text-area'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/field-text-area' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/field-text-area/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/es/components/FieldTextArea' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/es/components/FieldTextAreaStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/es/styled/TextArea' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/field-text-area/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/bundle-cjs'>;
}
declare module '@atlaskit/field-text-area/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/field-text-area/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/bundle'>;
}
declare module '@atlaskit/field-text-area/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/bundle.min'>;
}
declare module '@atlaskit/field-text-area/dist/es/components/FieldTextArea.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/es/components/FieldTextArea'>;
}
declare module '@atlaskit/field-text-area/dist/es/components/FieldTextAreaStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/es/components/FieldTextAreaStateless'>;
}
declare module '@atlaskit/field-text-area/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/es/index'>;
}
declare module '@atlaskit/field-text-area/dist/es/styled/TextArea.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/es/styled/TextArea'>;
}
