// flow-typed signature: 718f2011d7bc39df7d8c7d9b902cb4be
// flow-typed version: <<STUB>>/@atlaskit/field-text_v4.0.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/field-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/field-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/field-text/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text/dist/es/components/FieldText' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text/dist/es/components/FieldTextStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text/dist/es/styled/Input' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/field-text/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/field-text/dist/bundle-cjs'>;
}
declare module '@atlaskit/field-text/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/field-text/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/field-text/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/field-text/dist/bundle'>;
}
declare module '@atlaskit/field-text/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/field-text/dist/bundle.min'>;
}
declare module '@atlaskit/field-text/dist/es/components/FieldText.js' {
  declare module.exports: $Exports<'@atlaskit/field-text/dist/es/components/FieldText'>;
}
declare module '@atlaskit/field-text/dist/es/components/FieldTextStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-text/dist/es/components/FieldTextStateless'>;
}
declare module '@atlaskit/field-text/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-text/dist/es/index'>;
}
declare module '@atlaskit/field-text/dist/es/styled/Input.js' {
  declare module.exports: $Exports<'@atlaskit/field-text/dist/es/styled/Input'>;
}
