// flow-typed signature: 374919176a9f512a5115b7dfcca87fcc
// flow-typed version: <<STUB>>/@atlaskit/field-text-area_v1.1.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/field-text-area'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/field-text-area' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/field-text-area/dist/cjs/FieldTextArea' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/cjs/FieldTextAreaStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/cjs/styled/TextArea' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/esm/FieldTextArea' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/esm/FieldTextAreaStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text-area/dist/esm/styled/TextArea' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/field-text-area/dist/cjs/FieldTextArea.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/cjs/FieldTextArea'>;
}
declare module '@atlaskit/field-text-area/dist/cjs/FieldTextAreaStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/cjs/FieldTextAreaStateless'>;
}
declare module '@atlaskit/field-text-area/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/cjs/index'>;
}
declare module '@atlaskit/field-text-area/dist/cjs/styled/TextArea.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/cjs/styled/TextArea'>;
}
declare module '@atlaskit/field-text-area/dist/esm/FieldTextArea.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/esm/FieldTextArea'>;
}
declare module '@atlaskit/field-text-area/dist/esm/FieldTextAreaStateless.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/esm/FieldTextAreaStateless'>;
}
declare module '@atlaskit/field-text-area/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/esm/index'>;
}
declare module '@atlaskit/field-text-area/dist/esm/styled/TextArea.js' {
  declare module.exports: $Exports<'@atlaskit/field-text-area/dist/esm/styled/TextArea'>;
}
