// flow-typed signature: ebcb51cb6cf377cc5a76d23826a971b4
// flow-typed version: <<STUB>>/@atlaskit/flag_v6.1.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/flag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/flag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/flag/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/components/AutoDismissFlag' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/components/Expander' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/components/Flag' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/components/FlagActions' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/components/FlagAnimationWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/components/FlagGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/styled/Actions' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/styled/Expander' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/styled/Flag' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/styled/Group' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/styled/Wrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/theme' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/es/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/flag/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/bundle-cjs'>;
}
declare module '@atlaskit/flag/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/flag/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/bundle'>;
}
declare module '@atlaskit/flag/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/bundle.min'>;
}
declare module '@atlaskit/flag/dist/es/components/AutoDismissFlag.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/components/AutoDismissFlag'>;
}
declare module '@atlaskit/flag/dist/es/components/Expander.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/components/Expander'>;
}
declare module '@atlaskit/flag/dist/es/components/Flag.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/components/Flag'>;
}
declare module '@atlaskit/flag/dist/es/components/FlagActions.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/components/FlagActions'>;
}
declare module '@atlaskit/flag/dist/es/components/FlagAnimationWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/components/FlagAnimationWrapper'>;
}
declare module '@atlaskit/flag/dist/es/components/FlagGroup.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/components/FlagGroup'>;
}
declare module '@atlaskit/flag/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/index'>;
}
declare module '@atlaskit/flag/dist/es/styled/Actions.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/styled/Actions'>;
}
declare module '@atlaskit/flag/dist/es/styled/Expander.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/styled/Expander'>;
}
declare module '@atlaskit/flag/dist/es/styled/Flag.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/styled/Flag'>;
}
declare module '@atlaskit/flag/dist/es/styled/Group.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/styled/Group'>;
}
declare module '@atlaskit/flag/dist/es/styled/Wrapper.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/styled/Wrapper'>;
}
declare module '@atlaskit/flag/dist/es/theme.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/theme'>;
}
declare module '@atlaskit/flag/dist/es/types.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/es/types'>;
}
