// flow-typed signature: ffaecf139a742d5e62bc940b4b700e44
// flow-typed version: <<STUB>>/@atlaskit/flag_v6.3.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/flag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/flag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/flag/dist/cjs/components/AutoDismissFlag/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/components/Expander/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/components/Expander/styledExpander' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/components/Flag/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/components/Flag/styledFlag' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/components/FlagActions/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/components/FlagActions/styledFlagActions' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/components/FlagGroup/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/components/FlagGroup/styledFlagGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/styled/Wrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/theme' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/AutoDismissFlag/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/Expander/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/Expander/styledExpander' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/Flag/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/Flag/styledFlag' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/FlagActions/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/FlagActions/styledFlagActions' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/FlagGroup/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/components/FlagGroup/styledFlagGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/styled/Wrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/theme' {
  declare module.exports: any;
}

declare module '@atlaskit/flag/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/flag/dist/cjs/components/AutoDismissFlag/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/AutoDismissFlag/index'>;
}
declare module '@atlaskit/flag/dist/cjs/components/Expander/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/Expander/index'>;
}
declare module '@atlaskit/flag/dist/cjs/components/Expander/styledExpander.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/Expander/styledExpander'>;
}
declare module '@atlaskit/flag/dist/cjs/components/Flag/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/Flag/index'>;
}
declare module '@atlaskit/flag/dist/cjs/components/Flag/styledFlag.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/Flag/styledFlag'>;
}
declare module '@atlaskit/flag/dist/cjs/components/FlagActions/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/FlagActions/index'>;
}
declare module '@atlaskit/flag/dist/cjs/components/FlagActions/styledFlagActions.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/FlagActions/styledFlagActions'>;
}
declare module '@atlaskit/flag/dist/cjs/components/FlagGroup/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/FlagGroup/index'>;
}
declare module '@atlaskit/flag/dist/cjs/components/FlagGroup/styledFlagGroup.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/components/FlagGroup/styledFlagGroup'>;
}
declare module '@atlaskit/flag/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/index'>;
}
declare module '@atlaskit/flag/dist/cjs/styled/Wrapper.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/styled/Wrapper'>;
}
declare module '@atlaskit/flag/dist/cjs/theme.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/theme'>;
}
declare module '@atlaskit/flag/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/cjs/types'>;
}
declare module '@atlaskit/flag/dist/esm/components/AutoDismissFlag/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/AutoDismissFlag/index'>;
}
declare module '@atlaskit/flag/dist/esm/components/Expander/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/Expander/index'>;
}
declare module '@atlaskit/flag/dist/esm/components/Expander/styledExpander.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/Expander/styledExpander'>;
}
declare module '@atlaskit/flag/dist/esm/components/Flag/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/Flag/index'>;
}
declare module '@atlaskit/flag/dist/esm/components/Flag/styledFlag.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/Flag/styledFlag'>;
}
declare module '@atlaskit/flag/dist/esm/components/FlagActions/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/FlagActions/index'>;
}
declare module '@atlaskit/flag/dist/esm/components/FlagActions/styledFlagActions.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/FlagActions/styledFlagActions'>;
}
declare module '@atlaskit/flag/dist/esm/components/FlagGroup/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/FlagGroup/index'>;
}
declare module '@atlaskit/flag/dist/esm/components/FlagGroup/styledFlagGroup.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/components/FlagGroup/styledFlagGroup'>;
}
declare module '@atlaskit/flag/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/index'>;
}
declare module '@atlaskit/flag/dist/esm/styled/Wrapper.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/styled/Wrapper'>;
}
declare module '@atlaskit/flag/dist/esm/theme.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/theme'>;
}
declare module '@atlaskit/flag/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/flag/dist/esm/types'>;
}
