// flow-typed signature: b3ffa33fd538040ee35367f8c07962b1
// flow-typed version: <<STUB>>/@atlaskit/icon_v10.8.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/icon/dist/cjs/components/Icon' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/dist/esm/components/Icon' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/dist/esm/es5/components/Icon' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/dist/esm/es5/index' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/dist/esm/es5/types' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/dist/esm/types' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/es5/components/Icon' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/es5/index' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/es5/types' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/activity' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/add-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/add-item' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/add' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/addon' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/app-access' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/arrow-down-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/arrow-down' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/arrow-left-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/arrow-left' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/arrow-right-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/arrow-right' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/arrow-up-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/arrow-up' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/atlassian' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/attachment' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/audio-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/audio' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/backlog' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/billing-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/billing' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/branches' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/builds' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/clone' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/commits' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/compare' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/forks' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/output' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/pipelines' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/pullrequests' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/repos' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/snippets' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bitbucket/source' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/board' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/book' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/bullet-list' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/calendar-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/calendar' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/camera-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/camera-rotate' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/camera-take-picture' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/camera' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/canvas' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/check-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/check' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/checkbox' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/chevron-down-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/chevron-down' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/chevron-left-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/chevron-left' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/chevron-right-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/chevron-right' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/chevron-up-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/chevron-up' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/code' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/comment' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/component' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/confluence' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/copy' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/creditcard-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/creditcard' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/cross-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/cross' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/dashboard' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/decision' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/detail-view' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/discover-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/discover' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/document-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/document' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/documents' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/download' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/dropbox' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/edit-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/edit' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/add' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/addon' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/advanced' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/align-center' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/align-left' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/align-right' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/attachment' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/bold' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/bullet-list' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/close' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/code' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/date' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/decision' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/done' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/edit' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/emoji' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/error' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/feedback' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/file' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/help' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/hint' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/image-border' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/image-resize' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/image' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/indent' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/info' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/italic' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/link' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/media-center' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/media-full-width' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/media-wide' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/media-wrap-left' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/media-wrap-right' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/mention' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/more' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/note' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/number-list' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/open' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/outdent' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/panel' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/photo' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/quote' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/recent' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/redo' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/remove' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/search' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/strikethrough' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/success' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/table' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/task' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/text-color' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/text-style' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/underline' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/undo' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/unlink' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/editor/warning' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/email' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/activity' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/atlassian' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/custom' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/emoji' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/flags' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/food' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/frequent' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/keyboard' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/nature' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/objects' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/people' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/symbols' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/emoji/travel' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/error' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/export' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/feedback' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/file' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/filter' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/flag-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/folder-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/folder' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/followers' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/following' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/googledrive' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/graph-bar' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/graph-line' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/gsuite' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/highlights' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/audio-only' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/chevron-double-down' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/chevron-double-up' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/chevron-down' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/chevron-up' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/dial-out' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/lobby' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/media-attachment-count' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/outgoing-sound' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/hipchat/sd-video' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/home-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/home-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/image-border' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/image-resize' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/image' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/info' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/invite-team' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/issue-raise' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/issue' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/issues' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira-core' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira-service-desk' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira-software' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/blocker' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/capture' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/critical' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/failed-build-status' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/labs' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/major' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/medium' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/minor' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/test-session' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/jira/trivial' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/lightbulb-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/lightbulb' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/link-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/link' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/list' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/location' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/lock-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/lock-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/lock' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/marketplace' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/actual-size' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/add-comment' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/annotate' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/arrow' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/audio' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/blur' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/brush' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/button-option' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/code' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/document' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/filter' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/grid' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/image' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/line-thickness' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/line' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/open-mediaviewer' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/oval' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/pdf' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/preselected' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/presentation' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/rectangle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/scale-large' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/scale-small' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/spreadsheet' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/text' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/unknown' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/video' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/zip' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/zoom-in' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/media-services/zoom-out' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/mention' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/menu' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/more-vertical' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/more' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/notification-all' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/notification-direct' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/notification' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/office-building-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/office-building' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/open' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/overview' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/page-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/page' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/pdf' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/people-group' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/people' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/person-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/person' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/portfolio' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/preferences' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/presence-active' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/presence-busy' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/presence-unavailable' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/question-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/question' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/queues' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/quote' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/radio' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/recent' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/redo' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/refresh' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/room-menu' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/schedule-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/schedule' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/screen' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/search' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/send' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/settings' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/share' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/ship' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/shortcut' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/sign-in' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/sign-out' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/star-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/star' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/statuspage' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/stride' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/subtask' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/switcher' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/table' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/task' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/trash' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/tray' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/undo' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/unlink' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/unlock-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/unlock-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/unlock' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/upload' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/user-avatar-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-audio-muted' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-audio-on' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-backward' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-camera-off' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-connection-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-forward' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-full-screen-off' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-full-screen-on' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-hang-up' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-hd-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-pause' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-play' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-raised-hand' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-share-screen' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/vid-speaking-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/video-circle' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/video-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/warning' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/watch-filled' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/watch' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/world-small' {
  declare module.exports: any;
}

declare module '@atlaskit/icon/glyph/world' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/icon/dist/cjs/components/Icon.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/cjs/components/Icon'>;
}
declare module '@atlaskit/icon/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/cjs/index'>;
}
declare module '@atlaskit/icon/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/cjs/types'>;
}
declare module '@atlaskit/icon/dist/esm/components/Icon.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/esm/components/Icon'>;
}
declare module '@atlaskit/icon/dist/esm/es5/components/Icon.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/esm/es5/components/Icon'>;
}
declare module '@atlaskit/icon/dist/esm/es5/index.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/esm/es5/index'>;
}
declare module '@atlaskit/icon/dist/esm/es5/types.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/esm/es5/types'>;
}
declare module '@atlaskit/icon/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/esm/index'>;
}
declare module '@atlaskit/icon/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/icon/dist/esm/types'>;
}
declare module '@atlaskit/icon/es5/components/Icon.js' {
  declare module.exports: $Exports<'@atlaskit/icon/es5/components/Icon'>;
}
declare module '@atlaskit/icon/es5/index.js' {
  declare module.exports: $Exports<'@atlaskit/icon/es5/index'>;
}
declare module '@atlaskit/icon/es5/types.js' {
  declare module.exports: $Exports<'@atlaskit/icon/es5/types'>;
}
declare module '@atlaskit/icon/glyph/activity.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/activity'>;
}
declare module '@atlaskit/icon/glyph/add-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/add-circle'>;
}
declare module '@atlaskit/icon/glyph/add-item.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/add-item'>;
}
declare module '@atlaskit/icon/glyph/add.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/add'>;
}
declare module '@atlaskit/icon/glyph/addon.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/addon'>;
}
declare module '@atlaskit/icon/glyph/app-access.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/app-access'>;
}
declare module '@atlaskit/icon/glyph/arrow-down-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/arrow-down-circle'>;
}
declare module '@atlaskit/icon/glyph/arrow-down.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/arrow-down'>;
}
declare module '@atlaskit/icon/glyph/arrow-left-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/arrow-left-circle'>;
}
declare module '@atlaskit/icon/glyph/arrow-left.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/arrow-left'>;
}
declare module '@atlaskit/icon/glyph/arrow-right-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/arrow-right-circle'>;
}
declare module '@atlaskit/icon/glyph/arrow-right.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/arrow-right'>;
}
declare module '@atlaskit/icon/glyph/arrow-up-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/arrow-up-circle'>;
}
declare module '@atlaskit/icon/glyph/arrow-up.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/arrow-up'>;
}
declare module '@atlaskit/icon/glyph/atlassian.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/atlassian'>;
}
declare module '@atlaskit/icon/glyph/attachment.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/attachment'>;
}
declare module '@atlaskit/icon/glyph/audio-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/audio-circle'>;
}
declare module '@atlaskit/icon/glyph/audio.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/audio'>;
}
declare module '@atlaskit/icon/glyph/backlog.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/backlog'>;
}
declare module '@atlaskit/icon/glyph/billing-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/billing-filled'>;
}
declare module '@atlaskit/icon/glyph/billing.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/billing'>;
}
declare module '@atlaskit/icon/glyph/bitbucket.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/branches.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/branches'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/builds.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/builds'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/clone.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/clone'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/commits.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/commits'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/compare.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/compare'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/forks.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/forks'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/output.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/output'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/pipelines.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/pipelines'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/pullrequests.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/pullrequests'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/repos.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/repos'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/snippets.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/snippets'>;
}
declare module '@atlaskit/icon/glyph/bitbucket/source.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bitbucket/source'>;
}
declare module '@atlaskit/icon/glyph/board.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/board'>;
}
declare module '@atlaskit/icon/glyph/book.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/book'>;
}
declare module '@atlaskit/icon/glyph/bullet-list.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/bullet-list'>;
}
declare module '@atlaskit/icon/glyph/calendar-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/calendar-filled'>;
}
declare module '@atlaskit/icon/glyph/calendar.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/calendar'>;
}
declare module '@atlaskit/icon/glyph/camera-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/camera-filled'>;
}
declare module '@atlaskit/icon/glyph/camera-rotate.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/camera-rotate'>;
}
declare module '@atlaskit/icon/glyph/camera-take-picture.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/camera-take-picture'>;
}
declare module '@atlaskit/icon/glyph/camera.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/camera'>;
}
declare module '@atlaskit/icon/glyph/canvas.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/canvas'>;
}
declare module '@atlaskit/icon/glyph/check-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/check-circle'>;
}
declare module '@atlaskit/icon/glyph/check.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/check'>;
}
declare module '@atlaskit/icon/glyph/checkbox.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/checkbox'>;
}
declare module '@atlaskit/icon/glyph/chevron-down-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/chevron-down-circle'>;
}
declare module '@atlaskit/icon/glyph/chevron-down.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/chevron-down'>;
}
declare module '@atlaskit/icon/glyph/chevron-left-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/chevron-left-circle'>;
}
declare module '@atlaskit/icon/glyph/chevron-left.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/chevron-left'>;
}
declare module '@atlaskit/icon/glyph/chevron-right-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/chevron-right-circle'>;
}
declare module '@atlaskit/icon/glyph/chevron-right.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/chevron-right'>;
}
declare module '@atlaskit/icon/glyph/chevron-up-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/chevron-up-circle'>;
}
declare module '@atlaskit/icon/glyph/chevron-up.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/chevron-up'>;
}
declare module '@atlaskit/icon/glyph/code.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/code'>;
}
declare module '@atlaskit/icon/glyph/comment.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/comment'>;
}
declare module '@atlaskit/icon/glyph/component.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/component'>;
}
declare module '@atlaskit/icon/glyph/confluence.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/confluence'>;
}
declare module '@atlaskit/icon/glyph/copy.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/copy'>;
}
declare module '@atlaskit/icon/glyph/creditcard-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/creditcard-filled'>;
}
declare module '@atlaskit/icon/glyph/creditcard.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/creditcard'>;
}
declare module '@atlaskit/icon/glyph/cross-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/cross-circle'>;
}
declare module '@atlaskit/icon/glyph/cross.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/cross'>;
}
declare module '@atlaskit/icon/glyph/dashboard.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/dashboard'>;
}
declare module '@atlaskit/icon/glyph/decision.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/decision'>;
}
declare module '@atlaskit/icon/glyph/detail-view.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/detail-view'>;
}
declare module '@atlaskit/icon/glyph/discover-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/discover-filled'>;
}
declare module '@atlaskit/icon/glyph/discover.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/discover'>;
}
declare module '@atlaskit/icon/glyph/document-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/document-filled'>;
}
declare module '@atlaskit/icon/glyph/document.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/document'>;
}
declare module '@atlaskit/icon/glyph/documents.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/documents'>;
}
declare module '@atlaskit/icon/glyph/download.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/download'>;
}
declare module '@atlaskit/icon/glyph/dropbox.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/dropbox'>;
}
declare module '@atlaskit/icon/glyph/edit-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/edit-filled'>;
}
declare module '@atlaskit/icon/glyph/edit.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/edit'>;
}
declare module '@atlaskit/icon/glyph/editor/add.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/add'>;
}
declare module '@atlaskit/icon/glyph/editor/addon.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/addon'>;
}
declare module '@atlaskit/icon/glyph/editor/advanced.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/advanced'>;
}
declare module '@atlaskit/icon/glyph/editor/align-center.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/align-center'>;
}
declare module '@atlaskit/icon/glyph/editor/align-left.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/align-left'>;
}
declare module '@atlaskit/icon/glyph/editor/align-right.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/align-right'>;
}
declare module '@atlaskit/icon/glyph/editor/attachment.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/attachment'>;
}
declare module '@atlaskit/icon/glyph/editor/bold.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/bold'>;
}
declare module '@atlaskit/icon/glyph/editor/bullet-list.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/bullet-list'>;
}
declare module '@atlaskit/icon/glyph/editor/close.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/close'>;
}
declare module '@atlaskit/icon/glyph/editor/code.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/code'>;
}
declare module '@atlaskit/icon/glyph/editor/date.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/date'>;
}
declare module '@atlaskit/icon/glyph/editor/decision.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/decision'>;
}
declare module '@atlaskit/icon/glyph/editor/done.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/done'>;
}
declare module '@atlaskit/icon/glyph/editor/edit.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/edit'>;
}
declare module '@atlaskit/icon/glyph/editor/emoji.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/emoji'>;
}
declare module '@atlaskit/icon/glyph/editor/error.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/error'>;
}
declare module '@atlaskit/icon/glyph/editor/feedback.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/feedback'>;
}
declare module '@atlaskit/icon/glyph/editor/file.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/file'>;
}
declare module '@atlaskit/icon/glyph/editor/help.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/help'>;
}
declare module '@atlaskit/icon/glyph/editor/hint.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/hint'>;
}
declare module '@atlaskit/icon/glyph/editor/image-border.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/image-border'>;
}
declare module '@atlaskit/icon/glyph/editor/image-resize.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/image-resize'>;
}
declare module '@atlaskit/icon/glyph/editor/image.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/image'>;
}
declare module '@atlaskit/icon/glyph/editor/indent.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/indent'>;
}
declare module '@atlaskit/icon/glyph/editor/info.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/info'>;
}
declare module '@atlaskit/icon/glyph/editor/italic.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/italic'>;
}
declare module '@atlaskit/icon/glyph/editor/link.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/link'>;
}
declare module '@atlaskit/icon/glyph/editor/media-center.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/media-center'>;
}
declare module '@atlaskit/icon/glyph/editor/media-full-width.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/media-full-width'>;
}
declare module '@atlaskit/icon/glyph/editor/media-wide.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/media-wide'>;
}
declare module '@atlaskit/icon/glyph/editor/media-wrap-left.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/media-wrap-left'>;
}
declare module '@atlaskit/icon/glyph/editor/media-wrap-right.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/media-wrap-right'>;
}
declare module '@atlaskit/icon/glyph/editor/mention.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/mention'>;
}
declare module '@atlaskit/icon/glyph/editor/more.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/more'>;
}
declare module '@atlaskit/icon/glyph/editor/note.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/note'>;
}
declare module '@atlaskit/icon/glyph/editor/number-list.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/number-list'>;
}
declare module '@atlaskit/icon/glyph/editor/open.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/open'>;
}
declare module '@atlaskit/icon/glyph/editor/outdent.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/outdent'>;
}
declare module '@atlaskit/icon/glyph/editor/panel.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/panel'>;
}
declare module '@atlaskit/icon/glyph/editor/photo.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/photo'>;
}
declare module '@atlaskit/icon/glyph/editor/quote.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/quote'>;
}
declare module '@atlaskit/icon/glyph/editor/recent.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/recent'>;
}
declare module '@atlaskit/icon/glyph/editor/redo.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/redo'>;
}
declare module '@atlaskit/icon/glyph/editor/remove.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/remove'>;
}
declare module '@atlaskit/icon/glyph/editor/search.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/search'>;
}
declare module '@atlaskit/icon/glyph/editor/strikethrough.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/strikethrough'>;
}
declare module '@atlaskit/icon/glyph/editor/success.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/success'>;
}
declare module '@atlaskit/icon/glyph/editor/table.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/table'>;
}
declare module '@atlaskit/icon/glyph/editor/task.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/task'>;
}
declare module '@atlaskit/icon/glyph/editor/text-color.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/text-color'>;
}
declare module '@atlaskit/icon/glyph/editor/text-style.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/text-style'>;
}
declare module '@atlaskit/icon/glyph/editor/underline.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/underline'>;
}
declare module '@atlaskit/icon/glyph/editor/undo.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/undo'>;
}
declare module '@atlaskit/icon/glyph/editor/unlink.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/unlink'>;
}
declare module '@atlaskit/icon/glyph/editor/warning.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/editor/warning'>;
}
declare module '@atlaskit/icon/glyph/email.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/email'>;
}
declare module '@atlaskit/icon/glyph/emoji.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji'>;
}
declare module '@atlaskit/icon/glyph/emoji/activity.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/activity'>;
}
declare module '@atlaskit/icon/glyph/emoji/atlassian.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/atlassian'>;
}
declare module '@atlaskit/icon/glyph/emoji/custom.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/custom'>;
}
declare module '@atlaskit/icon/glyph/emoji/emoji.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/emoji'>;
}
declare module '@atlaskit/icon/glyph/emoji/flags.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/flags'>;
}
declare module '@atlaskit/icon/glyph/emoji/food.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/food'>;
}
declare module '@atlaskit/icon/glyph/emoji/frequent.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/frequent'>;
}
declare module '@atlaskit/icon/glyph/emoji/keyboard.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/keyboard'>;
}
declare module '@atlaskit/icon/glyph/emoji/nature.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/nature'>;
}
declare module '@atlaskit/icon/glyph/emoji/objects.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/objects'>;
}
declare module '@atlaskit/icon/glyph/emoji/people.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/people'>;
}
declare module '@atlaskit/icon/glyph/emoji/symbols.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/symbols'>;
}
declare module '@atlaskit/icon/glyph/emoji/travel.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/emoji/travel'>;
}
declare module '@atlaskit/icon/glyph/error.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/error'>;
}
declare module '@atlaskit/icon/glyph/export.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/export'>;
}
declare module '@atlaskit/icon/glyph/feedback.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/feedback'>;
}
declare module '@atlaskit/icon/glyph/file.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/file'>;
}
declare module '@atlaskit/icon/glyph/filter.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/filter'>;
}
declare module '@atlaskit/icon/glyph/flag-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/flag-filled'>;
}
declare module '@atlaskit/icon/glyph/folder-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/folder-filled'>;
}
declare module '@atlaskit/icon/glyph/folder.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/folder'>;
}
declare module '@atlaskit/icon/glyph/followers.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/followers'>;
}
declare module '@atlaskit/icon/glyph/following.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/following'>;
}
declare module '@atlaskit/icon/glyph/googledrive.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/googledrive'>;
}
declare module '@atlaskit/icon/glyph/graph-bar.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/graph-bar'>;
}
declare module '@atlaskit/icon/glyph/graph-line.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/graph-line'>;
}
declare module '@atlaskit/icon/glyph/gsuite.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/gsuite'>;
}
declare module '@atlaskit/icon/glyph/highlights.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/highlights'>;
}
declare module '@atlaskit/icon/glyph/hipchat.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat'>;
}
declare module '@atlaskit/icon/glyph/hipchat/audio-only.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/audio-only'>;
}
declare module '@atlaskit/icon/glyph/hipchat/chevron-double-down.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/chevron-double-down'>;
}
declare module '@atlaskit/icon/glyph/hipchat/chevron-double-up.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/chevron-double-up'>;
}
declare module '@atlaskit/icon/glyph/hipchat/chevron-down.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/chevron-down'>;
}
declare module '@atlaskit/icon/glyph/hipchat/chevron-up.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/chevron-up'>;
}
declare module '@atlaskit/icon/glyph/hipchat/dial-out.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/dial-out'>;
}
declare module '@atlaskit/icon/glyph/hipchat/lobby.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/lobby'>;
}
declare module '@atlaskit/icon/glyph/hipchat/media-attachment-count.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/media-attachment-count'>;
}
declare module '@atlaskit/icon/glyph/hipchat/outgoing-sound.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/outgoing-sound'>;
}
declare module '@atlaskit/icon/glyph/hipchat/sd-video.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/hipchat/sd-video'>;
}
declare module '@atlaskit/icon/glyph/home-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/home-circle'>;
}
declare module '@atlaskit/icon/glyph/home-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/home-filled'>;
}
declare module '@atlaskit/icon/glyph/image-border.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/image-border'>;
}
declare module '@atlaskit/icon/glyph/image-resize.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/image-resize'>;
}
declare module '@atlaskit/icon/glyph/image.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/image'>;
}
declare module '@atlaskit/icon/glyph/info.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/info'>;
}
declare module '@atlaskit/icon/glyph/invite-team.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/invite-team'>;
}
declare module '@atlaskit/icon/glyph/issue-raise.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/issue-raise'>;
}
declare module '@atlaskit/icon/glyph/issue.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/issue'>;
}
declare module '@atlaskit/icon/glyph/issues.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/issues'>;
}
declare module '@atlaskit/icon/glyph/jira-core.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira-core'>;
}
declare module '@atlaskit/icon/glyph/jira-service-desk.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira-service-desk'>;
}
declare module '@atlaskit/icon/glyph/jira-software.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira-software'>;
}
declare module '@atlaskit/icon/glyph/jira.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira'>;
}
declare module '@atlaskit/icon/glyph/jira/blocker.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/blocker'>;
}
declare module '@atlaskit/icon/glyph/jira/capture.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/capture'>;
}
declare module '@atlaskit/icon/glyph/jira/critical.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/critical'>;
}
declare module '@atlaskit/icon/glyph/jira/failed-build-status.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/failed-build-status'>;
}
declare module '@atlaskit/icon/glyph/jira/labs.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/labs'>;
}
declare module '@atlaskit/icon/glyph/jira/major.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/major'>;
}
declare module '@atlaskit/icon/glyph/jira/medium.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/medium'>;
}
declare module '@atlaskit/icon/glyph/jira/minor.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/minor'>;
}
declare module '@atlaskit/icon/glyph/jira/test-session.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/test-session'>;
}
declare module '@atlaskit/icon/glyph/jira/trivial.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/jira/trivial'>;
}
declare module '@atlaskit/icon/glyph/lightbulb-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/lightbulb-filled'>;
}
declare module '@atlaskit/icon/glyph/lightbulb.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/lightbulb'>;
}
declare module '@atlaskit/icon/glyph/link-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/link-filled'>;
}
declare module '@atlaskit/icon/glyph/link.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/link'>;
}
declare module '@atlaskit/icon/glyph/list.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/list'>;
}
declare module '@atlaskit/icon/glyph/location.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/location'>;
}
declare module '@atlaskit/icon/glyph/lock-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/lock-circle'>;
}
declare module '@atlaskit/icon/glyph/lock-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/lock-filled'>;
}
declare module '@atlaskit/icon/glyph/lock.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/lock'>;
}
declare module '@atlaskit/icon/glyph/marketplace.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/marketplace'>;
}
declare module '@atlaskit/icon/glyph/media-services/actual-size.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/actual-size'>;
}
declare module '@atlaskit/icon/glyph/media-services/add-comment.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/add-comment'>;
}
declare module '@atlaskit/icon/glyph/media-services/annotate.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/annotate'>;
}
declare module '@atlaskit/icon/glyph/media-services/arrow.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/arrow'>;
}
declare module '@atlaskit/icon/glyph/media-services/audio.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/audio'>;
}
declare module '@atlaskit/icon/glyph/media-services/blur.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/blur'>;
}
declare module '@atlaskit/icon/glyph/media-services/brush.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/brush'>;
}
declare module '@atlaskit/icon/glyph/media-services/button-option.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/button-option'>;
}
declare module '@atlaskit/icon/glyph/media-services/code.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/code'>;
}
declare module '@atlaskit/icon/glyph/media-services/document.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/document'>;
}
declare module '@atlaskit/icon/glyph/media-services/filter.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/filter'>;
}
declare module '@atlaskit/icon/glyph/media-services/grid.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/grid'>;
}
declare module '@atlaskit/icon/glyph/media-services/image.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/image'>;
}
declare module '@atlaskit/icon/glyph/media-services/line-thickness.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/line-thickness'>;
}
declare module '@atlaskit/icon/glyph/media-services/line.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/line'>;
}
declare module '@atlaskit/icon/glyph/media-services/open-mediaviewer.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/open-mediaviewer'>;
}
declare module '@atlaskit/icon/glyph/media-services/oval.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/oval'>;
}
declare module '@atlaskit/icon/glyph/media-services/pdf.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/pdf'>;
}
declare module '@atlaskit/icon/glyph/media-services/preselected.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/preselected'>;
}
declare module '@atlaskit/icon/glyph/media-services/presentation.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/presentation'>;
}
declare module '@atlaskit/icon/glyph/media-services/rectangle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/rectangle'>;
}
declare module '@atlaskit/icon/glyph/media-services/scale-large.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/scale-large'>;
}
declare module '@atlaskit/icon/glyph/media-services/scale-small.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/scale-small'>;
}
declare module '@atlaskit/icon/glyph/media-services/spreadsheet.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/spreadsheet'>;
}
declare module '@atlaskit/icon/glyph/media-services/text.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/text'>;
}
declare module '@atlaskit/icon/glyph/media-services/unknown.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/unknown'>;
}
declare module '@atlaskit/icon/glyph/media-services/video.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/video'>;
}
declare module '@atlaskit/icon/glyph/media-services/zip.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/zip'>;
}
declare module '@atlaskit/icon/glyph/media-services/zoom-in.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/zoom-in'>;
}
declare module '@atlaskit/icon/glyph/media-services/zoom-out.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/media-services/zoom-out'>;
}
declare module '@atlaskit/icon/glyph/mention.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/mention'>;
}
declare module '@atlaskit/icon/glyph/menu.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/menu'>;
}
declare module '@atlaskit/icon/glyph/more-vertical.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/more-vertical'>;
}
declare module '@atlaskit/icon/glyph/more.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/more'>;
}
declare module '@atlaskit/icon/glyph/notification-all.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/notification-all'>;
}
declare module '@atlaskit/icon/glyph/notification-direct.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/notification-direct'>;
}
declare module '@atlaskit/icon/glyph/notification.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/notification'>;
}
declare module '@atlaskit/icon/glyph/office-building-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/office-building-filled'>;
}
declare module '@atlaskit/icon/glyph/office-building.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/office-building'>;
}
declare module '@atlaskit/icon/glyph/open.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/open'>;
}
declare module '@atlaskit/icon/glyph/overview.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/overview'>;
}
declare module '@atlaskit/icon/glyph/page-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/page-filled'>;
}
declare module '@atlaskit/icon/glyph/page.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/page'>;
}
declare module '@atlaskit/icon/glyph/pdf.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/pdf'>;
}
declare module '@atlaskit/icon/glyph/people-group.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/people-group'>;
}
declare module '@atlaskit/icon/glyph/people.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/people'>;
}
declare module '@atlaskit/icon/glyph/person-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/person-circle'>;
}
declare module '@atlaskit/icon/glyph/person.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/person'>;
}
declare module '@atlaskit/icon/glyph/portfolio.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/portfolio'>;
}
declare module '@atlaskit/icon/glyph/preferences.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/preferences'>;
}
declare module '@atlaskit/icon/glyph/presence-active.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/presence-active'>;
}
declare module '@atlaskit/icon/glyph/presence-busy.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/presence-busy'>;
}
declare module '@atlaskit/icon/glyph/presence-unavailable.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/presence-unavailable'>;
}
declare module '@atlaskit/icon/glyph/question-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/question-circle'>;
}
declare module '@atlaskit/icon/glyph/question.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/question'>;
}
declare module '@atlaskit/icon/glyph/queues.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/queues'>;
}
declare module '@atlaskit/icon/glyph/quote.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/quote'>;
}
declare module '@atlaskit/icon/glyph/radio.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/radio'>;
}
declare module '@atlaskit/icon/glyph/recent.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/recent'>;
}
declare module '@atlaskit/icon/glyph/redo.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/redo'>;
}
declare module '@atlaskit/icon/glyph/refresh.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/refresh'>;
}
declare module '@atlaskit/icon/glyph/room-menu.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/room-menu'>;
}
declare module '@atlaskit/icon/glyph/schedule-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/schedule-filled'>;
}
declare module '@atlaskit/icon/glyph/schedule.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/schedule'>;
}
declare module '@atlaskit/icon/glyph/screen.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/screen'>;
}
declare module '@atlaskit/icon/glyph/search.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/search'>;
}
declare module '@atlaskit/icon/glyph/send.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/send'>;
}
declare module '@atlaskit/icon/glyph/settings.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/settings'>;
}
declare module '@atlaskit/icon/glyph/share.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/share'>;
}
declare module '@atlaskit/icon/glyph/ship.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/ship'>;
}
declare module '@atlaskit/icon/glyph/shortcut.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/shortcut'>;
}
declare module '@atlaskit/icon/glyph/sign-in.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/sign-in'>;
}
declare module '@atlaskit/icon/glyph/sign-out.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/sign-out'>;
}
declare module '@atlaskit/icon/glyph/star-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/star-filled'>;
}
declare module '@atlaskit/icon/glyph/star.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/star'>;
}
declare module '@atlaskit/icon/glyph/statuspage.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/statuspage'>;
}
declare module '@atlaskit/icon/glyph/stride.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/stride'>;
}
declare module '@atlaskit/icon/glyph/subtask.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/subtask'>;
}
declare module '@atlaskit/icon/glyph/switcher.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/switcher'>;
}
declare module '@atlaskit/icon/glyph/table.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/table'>;
}
declare module '@atlaskit/icon/glyph/task.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/task'>;
}
declare module '@atlaskit/icon/glyph/trash.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/trash'>;
}
declare module '@atlaskit/icon/glyph/tray.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/tray'>;
}
declare module '@atlaskit/icon/glyph/undo.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/undo'>;
}
declare module '@atlaskit/icon/glyph/unlink.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/unlink'>;
}
declare module '@atlaskit/icon/glyph/unlock-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/unlock-circle'>;
}
declare module '@atlaskit/icon/glyph/unlock-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/unlock-filled'>;
}
declare module '@atlaskit/icon/glyph/unlock.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/unlock'>;
}
declare module '@atlaskit/icon/glyph/upload.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/upload'>;
}
declare module '@atlaskit/icon/glyph/user-avatar-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/user-avatar-circle'>;
}
declare module '@atlaskit/icon/glyph/vid-audio-muted.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-audio-muted'>;
}
declare module '@atlaskit/icon/glyph/vid-audio-on.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-audio-on'>;
}
declare module '@atlaskit/icon/glyph/vid-backward.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-backward'>;
}
declare module '@atlaskit/icon/glyph/vid-camera-off.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-camera-off'>;
}
declare module '@atlaskit/icon/glyph/vid-connection-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-connection-circle'>;
}
declare module '@atlaskit/icon/glyph/vid-forward.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-forward'>;
}
declare module '@atlaskit/icon/glyph/vid-full-screen-off.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-full-screen-off'>;
}
declare module '@atlaskit/icon/glyph/vid-full-screen-on.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-full-screen-on'>;
}
declare module '@atlaskit/icon/glyph/vid-hang-up.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-hang-up'>;
}
declare module '@atlaskit/icon/glyph/vid-hd-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-hd-circle'>;
}
declare module '@atlaskit/icon/glyph/vid-pause.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-pause'>;
}
declare module '@atlaskit/icon/glyph/vid-play.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-play'>;
}
declare module '@atlaskit/icon/glyph/vid-raised-hand.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-raised-hand'>;
}
declare module '@atlaskit/icon/glyph/vid-share-screen.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-share-screen'>;
}
declare module '@atlaskit/icon/glyph/vid-speaking-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/vid-speaking-circle'>;
}
declare module '@atlaskit/icon/glyph/video-circle.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/video-circle'>;
}
declare module '@atlaskit/icon/glyph/video-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/video-filled'>;
}
declare module '@atlaskit/icon/glyph/warning.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/warning'>;
}
declare module '@atlaskit/icon/glyph/watch-filled.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/watch-filled'>;
}
declare module '@atlaskit/icon/glyph/watch.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/watch'>;
}
declare module '@atlaskit/icon/glyph/world-small.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/world-small'>;
}
declare module '@atlaskit/icon/glyph/world.js' {
  declare module.exports: $Exports<'@atlaskit/icon/glyph/world'>;
}
