// flow-typed signature: 47af7b003e9b98e260ca38be6c1022b4
// flow-typed version: <<STUB>>/@atlaskit/inline-dialog_v5.0.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/inline-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/inline-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/inline-dialog/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/es/InlineDialog' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/es/styled' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/inline-dialog/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/bundle-cjs'>;
}
declare module '@atlaskit/inline-dialog/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/inline-dialog/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/bundle'>;
}
declare module '@atlaskit/inline-dialog/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/bundle.min'>;
}
declare module '@atlaskit/inline-dialog/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/es/index'>;
}
declare module '@atlaskit/inline-dialog/dist/es/InlineDialog.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/es/InlineDialog'>;
}
declare module '@atlaskit/inline-dialog/dist/es/styled.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/es/styled'>;
}
