// flow-typed signature: f91c163bfbe2103bce2e33828226e750
// flow-typed version: <<STUB>>/@atlaskit/inline-edit_v4.5.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/inline-edit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/inline-edit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/inline-edit/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/components/InlineEdit' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/components/InlineEditStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/styled/ButtonsWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/styled/ButtonWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/styled/ContentWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/styled/EditButton' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/styled/FieldBaseWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/styled/ReadViewContentWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/es/styled/RootWrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/inline-edit/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/bundle-cjs'>;
}
declare module '@atlaskit/inline-edit/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/inline-edit/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/bundle'>;
}
declare module '@atlaskit/inline-edit/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/bundle.min'>;
}
declare module '@atlaskit/inline-edit/dist/es/components/InlineEdit.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/components/InlineEdit'>;
}
declare module '@atlaskit/inline-edit/dist/es/components/InlineEditStateless.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/components/InlineEditStateless'>;
}
declare module '@atlaskit/inline-edit/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/index'>;
}
declare module '@atlaskit/inline-edit/dist/es/styled/ButtonsWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/styled/ButtonsWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/es/styled/ButtonWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/styled/ButtonWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/es/styled/ContentWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/styled/ContentWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/es/styled/EditButton.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/styled/EditButton'>;
}
declare module '@atlaskit/inline-edit/dist/es/styled/FieldBaseWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/styled/FieldBaseWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/es/styled/ReadViewContentWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/styled/ReadViewContentWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/es/styled/RootWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/es/styled/RootWrapper'>;
}
