// flow-typed signature: 58b1a3502948a6c1968768c1854155ab
// flow-typed version: <<STUB>>/@atlaskit/inline-edit_v4.5.14/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/inline-edit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/inline-edit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/inline-edit/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/InlineEdit' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/InlineEditStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/styled/ButtonsWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/styled/ButtonWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/styled/ContentWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/styled/EditButton' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/styled/FieldBaseWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/styled/ReadViewContentWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/cjs/styled/RootWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/InlineEdit' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/InlineEditStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/styled/ButtonsWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/styled/ButtonWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/styled/ContentWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/styled/EditButton' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/styled/FieldBaseWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/styled/ReadViewContentWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit/dist/esm/styled/RootWrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/inline-edit/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/index'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/InlineEdit.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/InlineEdit'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/InlineEditStateless.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/InlineEditStateless'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/styled/ButtonsWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/styled/ButtonsWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/styled/ButtonWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/styled/ButtonWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/styled/ContentWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/styled/ContentWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/styled/EditButton.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/styled/EditButton'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/styled/FieldBaseWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/styled/FieldBaseWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/styled/ReadViewContentWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/styled/ReadViewContentWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/cjs/styled/RootWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/cjs/styled/RootWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/index'>;
}
declare module '@atlaskit/inline-edit/dist/esm/InlineEdit.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/InlineEdit'>;
}
declare module '@atlaskit/inline-edit/dist/esm/InlineEditStateless.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/InlineEditStateless'>;
}
declare module '@atlaskit/inline-edit/dist/esm/styled/ButtonsWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/styled/ButtonsWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/esm/styled/ButtonWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/styled/ButtonWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/esm/styled/ContentWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/styled/ContentWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/esm/styled/EditButton.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/styled/EditButton'>;
}
declare module '@atlaskit/inline-edit/dist/esm/styled/FieldBaseWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/styled/FieldBaseWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/esm/styled/ReadViewContentWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/styled/ReadViewContentWrapper'>;
}
declare module '@atlaskit/inline-edit/dist/esm/styled/RootWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/inline-edit/dist/esm/styled/RootWrapper'>;
}
