// flow-typed signature: 85a83a58cca5ac1c73fd4d6f38330394
// flow-typed version: <<STUB>>/@atlaskit/inline-dialog_v5.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/inline-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/inline-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/inline-dialog/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/cjs/InlineDialog/index' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/cjs/InlineDialog/styled' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/esm/InlineDialog/index' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/esm/InlineDialog/styled' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-dialog/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/inline-dialog/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/cjs/index'>;
}
declare module '@atlaskit/inline-dialog/dist/cjs/InlineDialog/index.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/cjs/InlineDialog/index'>;
}
declare module '@atlaskit/inline-dialog/dist/cjs/InlineDialog/styled.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/cjs/InlineDialog/styled'>;
}
declare module '@atlaskit/inline-dialog/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/cjs/types'>;
}
declare module '@atlaskit/inline-dialog/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/esm/index'>;
}
declare module '@atlaskit/inline-dialog/dist/esm/InlineDialog/index.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/esm/InlineDialog/index'>;
}
declare module '@atlaskit/inline-dialog/dist/esm/InlineDialog/styled.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/esm/InlineDialog/styled'>;
}
declare module '@atlaskit/inline-dialog/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/inline-dialog/dist/esm/types'>;
}
