// flow-typed signature: 38b6d8bd1781ad4a8439926144095121
// flow-typed version: <<STUB>>/@atlaskit/input_v1.6.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/input/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/input/dist/cjs/SingleLineTextInput' {
  declare module.exports: any;
}

declare module '@atlaskit/input/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/input/dist/esm/SingleLineTextInput' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/input/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/input/dist/cjs/index'>;
}
declare module '@atlaskit/input/dist/cjs/SingleLineTextInput.js' {
  declare module.exports: $Exports<'@atlaskit/input/dist/cjs/SingleLineTextInput'>;
}
declare module '@atlaskit/input/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/input/dist/esm/index'>;
}
declare module '@atlaskit/input/dist/esm/SingleLineTextInput.js' {
  declare module.exports: $Exports<'@atlaskit/input/dist/esm/SingleLineTextInput'>;
}
