// flow-typed signature: 3a2bc252fbdd93af83b43e6d63b46cb9
// flow-typed version: <<STUB>>/@atlaskit/modal-dialog_v3.3.10/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/modal-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/modal-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/modal-dialog/dist/cjs/components/Animation' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/components/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/components/Footer' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/components/Header' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/components/Modal' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/components/ScrollLock' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/shared-variables' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/styled/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/styled/Modal' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/utils/flex-max-height-ie-fix' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/utils/focus-scope' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/cjs/utils/focus-store' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/components/Animation' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/components/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/components/Footer' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/components/Header' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/components/Modal' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/components/ScrollLock' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/shared-variables' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/styled/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/styled/Modal' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/types' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/utils/flex-max-height-ie-fix' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/utils/focus-scope' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/esm/utils/focus-store' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/modal-dialog/dist/cjs/components/Animation.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/components/Animation'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/components/Content.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/components/Content'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/components/Footer.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/components/Footer'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/components/Header.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/components/Header'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/components/Modal.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/components/Modal'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/components/ScrollLock.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/components/ScrollLock'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/index'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/shared-variables.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/shared-variables'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/styled/Content.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/styled/Content'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/styled/Modal.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/styled/Modal'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/types'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/utils/flex-max-height-ie-fix.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/utils/flex-max-height-ie-fix'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/utils/focus-scope.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/utils/focus-scope'>;
}
declare module '@atlaskit/modal-dialog/dist/cjs/utils/focus-store.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/cjs/utils/focus-store'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/components/Animation.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/components/Animation'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/components/Content.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/components/Content'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/components/Footer.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/components/Footer'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/components/Header.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/components/Header'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/components/Modal.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/components/Modal'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/components/ScrollLock.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/components/ScrollLock'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/index'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/shared-variables.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/shared-variables'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/styled/Content.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/styled/Content'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/styled/Modal.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/styled/Modal'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/types'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/utils/flex-max-height-ie-fix.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/utils/flex-max-height-ie-fix'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/utils/focus-scope.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/utils/focus-scope'>;
}
declare module '@atlaskit/modal-dialog/dist/esm/utils/focus-store.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/esm/utils/focus-store'>;
}
