// flow-typed signature: 06367b7d48e05d9f41d9fc7292f58d3e
// flow-typed version: <<STUB>>/@atlaskit/modal-dialog_v3.0.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/modal-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/modal-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/modal-dialog/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/components/Animation' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/components/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/components/Footer' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/components/Header' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/components/Modal' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/components/ScrollLock' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/shared-variables' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/styled/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/styled/Modal' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/types' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/utils/focus-scope' {
  declare module.exports: any;
}

declare module '@atlaskit/modal-dialog/dist/es/utils/focus-store' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/modal-dialog/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/bundle-cjs'>;
}
declare module '@atlaskit/modal-dialog/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/modal-dialog/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/bundle'>;
}
declare module '@atlaskit/modal-dialog/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/bundle.min'>;
}
declare module '@atlaskit/modal-dialog/dist/es/components/Animation.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/components/Animation'>;
}
declare module '@atlaskit/modal-dialog/dist/es/components/Content.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/components/Content'>;
}
declare module '@atlaskit/modal-dialog/dist/es/components/Footer.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/components/Footer'>;
}
declare module '@atlaskit/modal-dialog/dist/es/components/Header.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/components/Header'>;
}
declare module '@atlaskit/modal-dialog/dist/es/components/Modal.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/components/Modal'>;
}
declare module '@atlaskit/modal-dialog/dist/es/components/ScrollLock.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/components/ScrollLock'>;
}
declare module '@atlaskit/modal-dialog/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/index'>;
}
declare module '@atlaskit/modal-dialog/dist/es/shared-variables.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/shared-variables'>;
}
declare module '@atlaskit/modal-dialog/dist/es/styled/Content.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/styled/Content'>;
}
declare module '@atlaskit/modal-dialog/dist/es/styled/Modal.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/styled/Modal'>;
}
declare module '@atlaskit/modal-dialog/dist/es/types.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/types'>;
}
declare module '@atlaskit/modal-dialog/dist/es/utils/focus-scope.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/utils/focus-scope'>;
}
declare module '@atlaskit/modal-dialog/dist/es/utils/focus-store.js' {
  declare module.exports: $Exports<'@atlaskit/modal-dialog/dist/es/utils/focus-store'>;
}
