// flow-typed signature: 666561078dbb2b09b4468c3d25d9b0db
// flow-typed version: <<STUB>>/@atlaskit/single-select_v2.0.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/single-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/single-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/single-select/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/components/appearances' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/components/DummyGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/components/DummyItem' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/components/InitialLoading' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/components/NothingWasFound' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/components/SingleSelect' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/components/StatelessSelect' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/Autocomplete' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/ElemBefore' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/Expand' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/InitialLoading' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/NothingWasFound' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/Placeholder' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/placeholderStyles' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/StatelessSelectWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/es/styled/Trigger' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/single-select/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/bundle-cjs'>;
}
declare module '@atlaskit/single-select/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/single-select/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/bundle'>;
}
declare module '@atlaskit/single-select/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/bundle.min'>;
}
declare module '@atlaskit/single-select/dist/es/components/appearances.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/components/appearances'>;
}
declare module '@atlaskit/single-select/dist/es/components/DummyGroup.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/components/DummyGroup'>;
}
declare module '@atlaskit/single-select/dist/es/components/DummyItem.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/components/DummyItem'>;
}
declare module '@atlaskit/single-select/dist/es/components/InitialLoading.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/components/InitialLoading'>;
}
declare module '@atlaskit/single-select/dist/es/components/NothingWasFound.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/components/NothingWasFound'>;
}
declare module '@atlaskit/single-select/dist/es/components/SingleSelect.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/components/SingleSelect'>;
}
declare module '@atlaskit/single-select/dist/es/components/StatelessSelect.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/components/StatelessSelect'>;
}
declare module '@atlaskit/single-select/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/index'>;
}
declare module '@atlaskit/single-select/dist/es/styled/Autocomplete.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/Autocomplete'>;
}
declare module '@atlaskit/single-select/dist/es/styled/Content.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/Content'>;
}
declare module '@atlaskit/single-select/dist/es/styled/ElemBefore.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/ElemBefore'>;
}
declare module '@atlaskit/single-select/dist/es/styled/Expand.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/Expand'>;
}
declare module '@atlaskit/single-select/dist/es/styled/InitialLoading.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/InitialLoading'>;
}
declare module '@atlaskit/single-select/dist/es/styled/NothingWasFound.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/NothingWasFound'>;
}
declare module '@atlaskit/single-select/dist/es/styled/Placeholder.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/Placeholder'>;
}
declare module '@atlaskit/single-select/dist/es/styled/placeholderStyles.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/placeholderStyles'>;
}
declare module '@atlaskit/single-select/dist/es/styled/StatelessSelectWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/StatelessSelectWrapper'>;
}
declare module '@atlaskit/single-select/dist/es/styled/Trigger.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/es/styled/Trigger'>;
}
