// flow-typed signature: d2e192f2e23485cedd2c4c35d6084f90
// flow-typed version: <<STUB>>/@atlaskit/single-select_v3.2.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/single-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/single-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/single-select/dist/cjs/components/appearances' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/components/DummyGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/components/DummyItem' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/components/InitialLoading' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/components/NothingWasFound' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/components/SingleSelect' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/components/StatelessSelect' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/Autocomplete' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/ElemBefore' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/Expand' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/InitialLoading' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/NothingWasFound' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/Placeholder' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/placeholderStyles' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/StatelessSelectWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/styled/Trigger' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/components/appearances' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/components/DummyGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/components/DummyItem' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/components/InitialLoading' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/components/NothingWasFound' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/components/SingleSelect' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/components/StatelessSelect' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/Autocomplete' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/Content' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/ElemBefore' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/Expand' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/InitialLoading' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/NothingWasFound' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/Placeholder' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/placeholderStyles' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/StatelessSelectWrapper' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/styled/Trigger' {
  declare module.exports: any;
}

declare module '@atlaskit/single-select/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/single-select/dist/cjs/components/appearances.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/components/appearances'>;
}
declare module '@atlaskit/single-select/dist/cjs/components/DummyGroup.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/components/DummyGroup'>;
}
declare module '@atlaskit/single-select/dist/cjs/components/DummyItem.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/components/DummyItem'>;
}
declare module '@atlaskit/single-select/dist/cjs/components/InitialLoading.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/components/InitialLoading'>;
}
declare module '@atlaskit/single-select/dist/cjs/components/NothingWasFound.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/components/NothingWasFound'>;
}
declare module '@atlaskit/single-select/dist/cjs/components/SingleSelect.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/components/SingleSelect'>;
}
declare module '@atlaskit/single-select/dist/cjs/components/StatelessSelect.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/components/StatelessSelect'>;
}
declare module '@atlaskit/single-select/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/index'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/Autocomplete.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/Autocomplete'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/Content.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/Content'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/ElemBefore.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/ElemBefore'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/Expand.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/Expand'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/InitialLoading.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/InitialLoading'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/NothingWasFound.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/NothingWasFound'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/Placeholder.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/Placeholder'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/placeholderStyles.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/placeholderStyles'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/StatelessSelectWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/StatelessSelectWrapper'>;
}
declare module '@atlaskit/single-select/dist/cjs/styled/Trigger.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/styled/Trigger'>;
}
declare module '@atlaskit/single-select/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/cjs/types'>;
}
declare module '@atlaskit/single-select/dist/esm/components/appearances.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/components/appearances'>;
}
declare module '@atlaskit/single-select/dist/esm/components/DummyGroup.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/components/DummyGroup'>;
}
declare module '@atlaskit/single-select/dist/esm/components/DummyItem.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/components/DummyItem'>;
}
declare module '@atlaskit/single-select/dist/esm/components/InitialLoading.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/components/InitialLoading'>;
}
declare module '@atlaskit/single-select/dist/esm/components/NothingWasFound.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/components/NothingWasFound'>;
}
declare module '@atlaskit/single-select/dist/esm/components/SingleSelect.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/components/SingleSelect'>;
}
declare module '@atlaskit/single-select/dist/esm/components/StatelessSelect.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/components/StatelessSelect'>;
}
declare module '@atlaskit/single-select/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/index'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/Autocomplete.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/Autocomplete'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/Content.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/Content'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/ElemBefore.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/ElemBefore'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/Expand.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/Expand'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/InitialLoading.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/InitialLoading'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/NothingWasFound.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/NothingWasFound'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/Placeholder.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/Placeholder'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/placeholderStyles.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/placeholderStyles'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/StatelessSelectWrapper.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/StatelessSelectWrapper'>;
}
declare module '@atlaskit/single-select/dist/esm/styled/Trigger.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/styled/Trigger'>;
}
declare module '@atlaskit/single-select/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/single-select/dist/esm/types'>;
}
