// flow-typed signature: 4bfd962529391fb6bed6f651e30f6e7b
// flow-typed version: <<STUB>>/@atlaskit/spinner_v4.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/spinner/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/cjs/Spinner/constants' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/cjs/Spinner/index' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/cjs/Spinner/styledContainer' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/cjs/Spinner/styledSvg' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/esm/Spinner/constants' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/esm/Spinner/index' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/esm/Spinner/styledContainer' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/esm/Spinner/styledSvg' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/spinner/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/cjs/index'>;
}
declare module '@atlaskit/spinner/dist/cjs/Spinner/constants.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/cjs/Spinner/constants'>;
}
declare module '@atlaskit/spinner/dist/cjs/Spinner/index.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/cjs/Spinner/index'>;
}
declare module '@atlaskit/spinner/dist/cjs/Spinner/styledContainer.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/cjs/Spinner/styledContainer'>;
}
declare module '@atlaskit/spinner/dist/cjs/Spinner/styledSvg.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/cjs/Spinner/styledSvg'>;
}
declare module '@atlaskit/spinner/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/cjs/types'>;
}
declare module '@atlaskit/spinner/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/esm/index'>;
}
declare module '@atlaskit/spinner/dist/esm/Spinner/constants.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/esm/Spinner/constants'>;
}
declare module '@atlaskit/spinner/dist/esm/Spinner/index.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/esm/Spinner/index'>;
}
declare module '@atlaskit/spinner/dist/esm/Spinner/styledContainer.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/esm/Spinner/styledContainer'>;
}
declare module '@atlaskit/spinner/dist/esm/Spinner/styledSvg.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/esm/Spinner/styledSvg'>;
}
declare module '@atlaskit/spinner/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/esm/types'>;
}
