// flow-typed signature: e209abfb06814041a9b3c08ee6b0971d
// flow-typed version: <<STUB>>/@atlaskit/spinner_v4.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/spinner/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/es/Spinner' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/es/SpinnerGlyph' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/es/styled/Container' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/es/styled/Svg' {
  declare module.exports: any;
}

declare module '@atlaskit/spinner/dist/es/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/spinner/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/bundle-cjs'>;
}
declare module '@atlaskit/spinner/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/spinner/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/bundle'>;
}
declare module '@atlaskit/spinner/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/bundle.min'>;
}
declare module '@atlaskit/spinner/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/es/index'>;
}
declare module '@atlaskit/spinner/dist/es/Spinner.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/es/Spinner'>;
}
declare module '@atlaskit/spinner/dist/es/SpinnerGlyph.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/es/SpinnerGlyph'>;
}
declare module '@atlaskit/spinner/dist/es/styled/Container.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/es/styled/Container'>;
}
declare module '@atlaskit/spinner/dist/es/styled/Svg.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/es/styled/Svg'>;
}
declare module '@atlaskit/spinner/dist/es/types.js' {
  declare module.exports: $Exports<'@atlaskit/spinner/dist/es/types'>;
}
