// flow-typed signature: c5b2ab7f68419f5a2051c520414f241c
// flow-typed version: <<STUB>>/@atlaskit/tooltip_v6.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/tooltip/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/bundle.min' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/es/components/Tooltip' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/es/components/TooltipStateless' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/es/index' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/es/styled/Tooltip' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/es/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/tooltip/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/bundle-cjs'>;
}
declare module '@atlaskit/tooltip/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/tooltip/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/bundle'>;
}
declare module '@atlaskit/tooltip/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/bundle.min'>;
}
declare module '@atlaskit/tooltip/dist/es/components/Tooltip.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/es/components/Tooltip'>;
}
declare module '@atlaskit/tooltip/dist/es/components/TooltipStateless.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/es/components/TooltipStateless'>;
}
declare module '@atlaskit/tooltip/dist/es/index.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/es/index'>;
}
declare module '@atlaskit/tooltip/dist/es/styled/Tooltip.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/es/styled/Tooltip'>;
}
declare module '@atlaskit/tooltip/dist/es/utils.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/es/utils'>;
}
