// flow-typed signature: 006d8af5adc7da12b76f093410a0fe7d
// flow-typed version: <<STUB>>/@atlaskit/tooltip_v8.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/tooltip/dist/cjs/components/Animation' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/components/Marshal' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/components/Portal' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/components/Tooltip' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/components/Transition' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/components/utils/getPosition' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/components/utils/getStyle' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/components/utils/index' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/components/utils/inViewport' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/styled' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/Animation' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/Marshal' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/Portal' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/Tooltip' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/Transition' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/utils/getPosition' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/utils/getStyle' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/utils/index' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/components/utils/inViewport' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/index' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/styled' {
  declare module.exports: any;
}

declare module '@atlaskit/tooltip/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/tooltip/dist/cjs/components/Animation.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/Animation'>;
}
declare module '@atlaskit/tooltip/dist/cjs/components/Marshal.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/Marshal'>;
}
declare module '@atlaskit/tooltip/dist/cjs/components/Portal.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/Portal'>;
}
declare module '@atlaskit/tooltip/dist/cjs/components/Tooltip.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/Tooltip'>;
}
declare module '@atlaskit/tooltip/dist/cjs/components/Transition.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/Transition'>;
}
declare module '@atlaskit/tooltip/dist/cjs/components/utils/getPosition.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/utils/getPosition'>;
}
declare module '@atlaskit/tooltip/dist/cjs/components/utils/getStyle.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/utils/getStyle'>;
}
declare module '@atlaskit/tooltip/dist/cjs/components/utils/index.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/utils/index'>;
}
declare module '@atlaskit/tooltip/dist/cjs/components/utils/inViewport.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/components/utils/inViewport'>;
}
declare module '@atlaskit/tooltip/dist/cjs/index.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/index'>;
}
declare module '@atlaskit/tooltip/dist/cjs/styled.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/styled'>;
}
declare module '@atlaskit/tooltip/dist/cjs/types.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/cjs/types'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/Animation.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/Animation'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/Marshal.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/Marshal'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/Portal.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/Portal'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/Tooltip.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/Tooltip'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/Transition.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/Transition'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/utils/getPosition.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/utils/getPosition'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/utils/getStyle.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/utils/getStyle'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/utils/index.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/utils/index'>;
}
declare module '@atlaskit/tooltip/dist/esm/components/utils/inViewport.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/components/utils/inViewport'>;
}
declare module '@atlaskit/tooltip/dist/esm/index.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/index'>;
}
declare module '@atlaskit/tooltip/dist/esm/styled.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/styled'>;
}
declare module '@atlaskit/tooltip/dist/esm/types.js' {
  declare module.exports: $Exports<'@atlaskit/tooltip/dist/esm/types'>;
}
