export const FETCH_ISSUES_REQUEST = 'issues/FETCH_ISSUES_REQUEST';
export const FETCH_FILTER_ISSUES_REQUEST = 'issues/FETCH_FILTER_ISSUES_REQUEST';
export const FETCH_ISSUE_REQUEST = 'issues/FETCH_ISSUE_REQUEST';
export const FETCH_RECENT_ISSUES_REQUEST = 'issues/FETCH_RECENT_ISSUES_REQUEST';
export const FETCH_SEARCH_ISSUES_REQUEST = 'issues/FETCH_SEARCH_ISSUES_REQUEST';

export const FILL_ISSUES = 'issues/FILL';
export const FILL_RECENT_ISSUES = 'issues/FILL_RECENT';
export const MERGE_RECENT_ISSUES = 'issues/MERGE_RECENT';
export const FILL_SEARCH_ISSUES = 'issues/FILL_SEARCH';

export const SET_ISSUES_FETCH_STATE = 'issues/SET_FETCH_STATE';
export const SET_ISSUES_FETCHED_STATE = 'issues/SET_FETCHED_STATE';
export const SET_RECENT_ISSUES_FETCH_STATE = 'issues/SET_RECENT_FETCH_STATE';
export const SET_SEARCH_ISSUES_FETCH_STATE = 'issues/SET_SEARCH_FETCH_STATE';
export const SET_TRACKING_ISSUE = 'issues/SET_TRACKING_ISSUE';

export const SET_SHOWING_FILTER_CRITERIA_BLOCK = 'issues/SET_SHOWING_FILTER_CRITERIA_BLOCK';
export const FETCH_ISSUES_ALL_TYPES_REQUEST = 'issues/FETCH_ISSUES_ALL_TYPES_REQUEST';
export const FILL_ISSUES_ALL_TYPES = 'issues/FILL_ISSUES_ALL_TYPES';
export const SET_ISSUES_ALL_TYPES_FETCH_STATE = 'issues/SET_ISSUES_ALL_TYPES_FETCH_STATE';
export const SET_ISSUES_ALL_STATUSES_FETCH_STATE = 'issues/SET_ISSUES_ALL_STATUSES_FETCH_STATE';
export const FETCH_ISSUES_ALL_STATUSES_REQUEST = 'issues/FETCH_ISSUES_ALL_STATUSES_REQUEST';
export const FILL_ISSUES_ALL_STATUSES = 'issues/FILL_ISSUES_ALL_STATUSES';
export const SET_FILTER_OF_ISSUES_CRITERIA_FILTERS = 'issues/SET_FILTER_OF_ISSUES_CRITERIA_FILTERS';
export const SET_SAVED_ISSUES_CRITERIA_FILTER = 'issues/SET_SAVED_ISSUES_CRITERIA_FILTER';
export const SET_ISSUES_CRITERIA_FILTER = 'issues/SET_ISSUES_CRITERIA_FILTER';
export const DELETE_ISSUES_CRITERIA_FILTER = 'issues/DELETE_ISSUES_CRITERIA_FILTER';

export const SET_ISSUES_COUNT = 'issues/SET_COUNT';
export const SET_ISSUES_SEARCH_VALUE = 'issues/SET_ISSUES_SEARCH_VALUE';
export const SET_LAST_STOP_INDEX = 'issues/SET_LAST_STOP_INDEX';
export const CLEAR_ISSUES_SEARCH_RESULTS = 'issues/CLEAR_ISSUES_SEARCH_RESULTS';
export const CLEAR_CURRENT_SCREENSHOTS = 'issues/CLEAR_CURRENT_SCREENSHOTS';

export const SELECT_ISSUE = 'issues/SELECT';
export const SET_SELECTED_INDEX = 'issues/SET_SELECTED_INDEX';

export const ADD_CURRENT_SCREENSHOT = 'issues/ADD_CURRENT_SCREENSHOT';

export const CLEAR_ISSUES = 'issues/CLEAR';
