export const FETCH_ISSUES_REQUEST = 'issues/FETCH_ISSUES_REQUEST';
export const FETCH_ISSUE_REQUEST = 'issues/FETCH_ISSUE_REQUEST';
export const FETCH_RECENT_ISSUES_REQUEST = 'issues/FETCH_RECENT_ISSUES_REQUEST';
export const FETCH_SEARCH_ISSUES_REQUEST = 'issues/FETCH_SEARCH_ISSUES_REQUEST';

export const FILL_ISSUES = 'issues/FILL';
export const FILL_RECENT_ISSUES = 'issues/FILL_RECENT';
export const FILL_SEARCH_ISSUES = 'issues/FILL_SEARCH';

export const SET_ISSUES_FETCH_STATE = 'issues/SET_FETCH_STATE';
export const SET_ISSUES_FETCHED_STATE = 'issues/SET_FETCHED_STATE';
export const SET_RECENT_ISSUES_FETCH_STATE = 'issues/SET_RECENT_FETCH_STATE';
export const SET_SEARCH_ISSUES_FETCH_STATE = 'issues/SET_SEARCH_FETCH_STATE';
export const SET_TRACKING_ISSUE = 'issues/SET_TRACKING_ISSUE';

export const SET_ISSUES_COUNT = 'issues/SET_COUNT';
export const SET_ISSUES_SEARCH_VALUE = 'issues/SET_ISSUES_SEARCH_VALUE';
export const SET_LAST_STOP_INDEX = 'issues/SET_LAST_STOP_INDEX';
export const CLEAR_ISSUES_SEARCH_RESULTS = 'issues/CLEAR_ISSUES_SEARCH_RESULTS';

export const SELECT_ISSUE = 'issues/SELECT';
export const SET_SELECTED_INDEX = 'issues/SET_SELECTED_INDEX';

export const CLEAR_ISSUES = 'issues/CLEAR';
