export const OPEN_DESCRIPTION_POPUP = 'ui/OPEN_DESCRIPTION_POPUP';
export const CLOSE_DESCRIPTION_POPUP = 'ui/CLOSE_DESCRIPTION_POPUP';
export const SET_SIDEBAR_TYPE = 'ui/SET_SIDEBAR_TYPE';
export const SET_IDLE_STATE = 'ui/SET_IDLE_STATE';
export const SET_UPDATE_FETCH_STATE = 'ui/SET_UPDATE_FETCH_STATE';
export const NOTIFY_UPDATE_AVAILABLE = 'ui/NOTIFY_UPDATE_AVAILABLE'; 
export const SET_UPDATE_DOWNLOAD_STATE = 'ui/SET_UPDATE_DOWNLOAD_STATE';
