export const SET_UPDATE_DOWNLOAD_STATE = 'ui/SET_UPDATE_DOWNLOAD_STATE';
export const NOTIFY_UPDATE_AVAILABLE = 'ui/NOTIFY_UPDATE_AVAILABLE';
export const SET_UPDATE_FETCH_STATE = 'ui/SET_UPDATE_FETCH_STATE';
export const SET_SIDEBAR_TYPE = 'ui/SET_SIDEBAR_TYPE';
