export const SET_UPDATE_DOWNLOAD_STATE = 'ui/SET_UPDATE_DOWNLOAD_STATE';
export const NOTIFY_UPDATE_AVAILABLE = 'ui/NOTIFY_UPDATE_AVAILABLE';
export const SET_UPDATE_FETCH_STATE = 'ui/SET_UPDATE_FETCH_STATE';
export const SET_SIDEBAR_TYPE = 'ui/SET_SIDEBAR_TYPE';
export const SET_SHOW_SETTINGS_MODAL = 'ui/SET_SHOW_SETTINGS_MODAL';
export const LOCAL_DESKTOP_SETTINGS_REQUEST = 'ui/LOCAL_DESKTOP_SETTINGS_REQUEST';
