export const FILL_WORKLOGS = 'worklogs/FILL';
export const FILL_RECENT_WORKLOGS = 'worklogs/FILL_RECENT';
export const ADD_RECENT_WORKLOG = 'worklogs/ADD_RECENT_WORKLOG';
export const CLEAR_WORKLOGS = 'worklogs/CLEAR';

export const SET_WORKLOGS_FETCH_STATE = 'worklogs/SET_FETCH_STATE';
export const SET_WORKLOG_UPLOAD_STATE = 'worklogs/SET_UPLOAD_STATE';
export const SET_CURRENT_DESCRIPTION = 'worklogs/SET_CURRENT_DESCRIPTION';
export const SET_STATE_CHECK_OFFLINE_SCREENSHOTS = 'worklogs/SET_STATE_CHECK_OFFLINE_SCREENSHOTS';

export const SELECT_WORKLOG_BY_ISSUE_ID = 'worklogs/SELECT_WORKLOG_BY_ISSUE_ID';
export const SELECT_WORKLOG = 'worklogs/SELECT_WORKLOG';

export const UPLOAD_SCREENSHOT_REQUEST = 'worklogs/UPLOAD_SCREENSHOT_REQUEST';
export const REJECT_SCREENSHOT_REQUEST = 'worklogs/REJECT_SCREENSHOT_REQUEST';

export const ADD_SCREENSHOT_TO_CURRENT_LIST = 'worklogs/ADD_SCREENSHOT_TO_CURRENT_LIST';
export const CLEAR_CURRENT_SCREENSHOTS_LIST = 'worklogs/CLEAR_CURRENT_SCREENSHOTS_LIST';

export const CHECK_OFFLINE_SCREENSHOTS = 'worklogs/CHECK_OFFLINE_SCREENSHOTS';
