export const FILL_WORKLOGS = 'worklogs/FILL';
export const FILL_RECENT_WORKLOGS = 'worklogs/FILL_RECENT';
export const CLEAR_WORKLOGS = 'worklogs/CLEAR';

export const SET_WORKLOGS_FETCH_STATE = 'worklogs/SET_FETCH_STATE';

export const SELECT_WORKLOG_BY_ISSUE_ID = 'worklogs/SELECT_WORKLOG_BY_ISSUE_ID';
export const SELECT_WORKLOG = 'worklogs/SELECT_WORKLOG';

export const UPLOAD_SCREENSHOT_REQUEST = 'worklogs/UPLOAD_SCREENSHOT_REQUEST';
export const SET_LAST_SCREENSHOT_TIME = 'worklogs/SET_LAST_SCREENSHOT_TIME';
export const REJECT_SCREENSHOT_REQUEST = 'worklogs/REJECT_SCREENSHOT_REQUEST';
