// @flow
export const SET_AUTH_FORM_STEP: 'ui/SET_AUTH_FORM_STEP' = 'ui/SET_AUTH_FORM_STEP';
export const SET_SIDEBAR_TYPE: 'ui/SET_SIDEBAR_TYPE' = 'ui/SET_SIDEBAR_TYPE';
export const SET_SIDEBAR_FILTERS_OPEN: 'ui/SET_SIDEBAR_FILTERS_OPEN' = 'ui/SET_SIDEBAR_FILTERS_OPEN';
export const SET_SETTINGS_MODAL_OPEN: 'ui/SET_SETTINGS_MODAL_OPEN' = 'ui/SET_SETTINGS_MODAL_OPEN';
export const SET_SUPPORT_MODAL_OPEN: 'ui/SET_SUPPORT_MODAL_OPEN' = 'ui/SET_SUPPORT_MODAL_OPEN';
export const SET_ABOUT_MODAL_OPEN: 'ui/SET_ABOUT_MODAL_OPEN' = 'ui/SET_ABOUT_MODAL_OPEN';
export const SET_ALERT_MODAL_OPEN: 'ui/SET_ALERT_MODAL_OPEN' = 'ui/SET_ALERT_MODAL_OPEN';
export const SET_ISSUE_VIEW_TAB: 'ui/SET_ISSUE_VIEW_TAB' = 'ui/SET_ISSUE_VIEW_TAB';
