// @flow

export const FETCH_ISSUES_REQUEST = 'issues/FETCH_REQUEST';
export const FETCH_RECENT_ISSUES_REQUEST = 'issues/FETCH_RECENT_REQUEST';
export const REFETCH_ISSUES_REQUEST = 'issues/REFETCH_REQUEST';
export const FETCH_NEW_ISSUE_REQUEST = 'issues/FETCH_NEW_ISSUE_REQUEST';
export const FETCH_UPDATE_ISSUE_REQUEST = 'issues/FETCH_UPDATE_ISSUE_REQUEST';
export const TRANSITION_ISSUE_REQUEST = 'issues/TRANSITION_ISSUE_REQUEST';
export const COMMENT_REQUEST = 'issues/COMMENT_REQUEST';
export const ASSIGN_ISSUE_REQUEST = 'issues/ASSIGN_ISSUE_REQUEST';
export const SELECT_ISSUE = 'issues/SELECT';
export const SHOW_ISSUE_FORM_WINDOW = 'issues/SHOW_ISSUE_FORM_WINDOW';
export const CLOSE_ISSUE_FORM_WINDOW = 'issues/CLOSE_ISSUE_FORM_WINDOW';
export const SHOW_ATTACHMENT_WINDOW = 'issues/SHOW_ATTACHMENT_WINDOW';
export const SET_ATTACHMENTS = 'issues/SET_ATTACHMENTS';
