export const TAKE_SCREENSHOT_REQUEST = 'TAKE_SCREENSHOT_REQUEST';
export const SET_NOTIFICATION_SCREENSHOT = 'SET_NOTIFICATION_SCREENSHOT';
export const TEST_SCREENSHOT_WINDOW_CLOSE = 'TEST_SCREENSHOT_WINDOW_CLOSE';
export const KEEP_SCREENSHOT = 'KEEP_SCREENSHOT';
export const DISMISS_ONLY_SCREENSHOT = 'DISMISS_ONLY_SCREENSHOT';
export const DISMISS_TIME_AND_SCREENSHOT = 'DISMISS_TIME_AND_SCREENSHOT';
export const ADD_SCREENSHOT = 'ADD_SCREENSHOT';
