// @flow

export const SET_UI_STATE = 'ui/SET_UI_STATE';
export const RESET_UI_STATE = 'ui/RESET_UI_STATE';
export const SET_MODAL_STATE = 'ui/SET_MODAL_STATE';
export const SET_ISSUES_FILTER = 'ui/SET_ISSUES_FILTER';
export const CHECK_FOR_UPDATES_REQUEST = 'ui/CHECK_FOR_UPDATES_REQUEST';
export const INSTALL_UPDATE_REQUEST = 'ui/INSTALL_UPDATE_REQUEST';
export const ADD_FLAG = 'ui/ADD_FLAG';
export const DELETE_FLAG = 'ui/DELETE_FLAG';
export const ISSUE_WORKLOGS_SCROLL_TO_INDEX_REQUEST = 'ui/ISSUE_WORKLOGS_SCROLL_TO_INDEX_REQUEST';
export const ACKNOWLEDGE_FEATURE = 'ui/ACKNOWLEDGE_FEATURE';
