
// @flow

export const SHOW_TEAM_STATUS_WINDOW = 'users/SHOW_TEAM_STATUS_WINDOW';
export const SET_TEAM_STATUS_USERS = 'users/SET_TEAM_STATUS_USERS';
export const FETCH_USERS_REQUEST = 'users/FETCH_USERS_REQUEST';
export const UPDATE_USER_TIMEZONE_REQUEST = 'users/UPDATE_USER_TIMEZONE_REQUEST';
